var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(c){var e=0;return function(){return e<c.length?{done:!1,value:c[e++]}:{done:!0}}};$jscomp.arrayIterator=function(c){return{next:$jscomp.arrayIteratorImpl(c)}};$jscomp.makeIterator=function(c){var e="undefined"!=typeof Symbol&&Symbol.iterator&&c[Symbol.iterator];return e?e.call(c):$jscomp.arrayIterator(c)};
$jscomp.getGlobal=function(c){c=["object"==typeof globalThis&&globalThis,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,c];for(var e=0;e<c.length;++e){var h=c[e];if(h&&h.Math==Math)return h}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,e,h){c!=Array.prototype&&c!=Object.prototype&&(c[e]=h.value)};$jscomp.polyfill=function(c,e,h,q){if(e){h=$jscomp.global;c=c.split(".");for(q=0;q<c.length-1;q++){var D=c[q];D in h||(h[D]={});h=h[D]}c=c[c.length-1];q=h[c];e=e(q);e!=q&&null!=e&&$jscomp.defineProperty(h,c,{configurable:!0,writable:!0,value:e})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(c){function e(){this.batch_=null}function h(c){return c instanceof D?c:new D(function(e,wc){e(c)})}if(c&&!$jscomp.FORCE_POLYFILL_PROMISE)return c;e.prototype.asyncExecute=function(c){if(null==this.batch_){this.batch_=[];var e=this;this.asyncExecuteFunction(function(){e.executeBatch_()})}this.batch_.push(c)};var q=$jscomp.global.setTimeout;e.prototype.asyncExecuteFunction=function(c){q(c,0)};e.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var c=
this.batch_;this.batch_=[];for(var e=0;e<c.length;++e){var h=c[e];c[e]=null;try{h()}catch(ma){this.asyncThrow_(ma)}}}this.batch_=null};e.prototype.asyncThrow_=function(c){this.asyncExecuteFunction(function(){throw c;})};var D=function(c){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var e=this.createResolveAndReject_();try{c(e.resolve,e.reject)}catch(kb){e.reject(kb)}};D.prototype.createResolveAndReject_=function(){function c(c){return function(wc){h||(h=!0,c.call(e,wc))}}var e=this,
h=!1;return{resolve:c(this.resolveTo_),reject:c(this.reject_)}};D.prototype.resolveTo_=function(c){if(c===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(c instanceof D)this.settleSameAsPromise_(c);else{a:switch(typeof c){case "object":var e=null!=c;break a;case "function":e=!0;break a;default:e=!1}e?this.resolveToNonPromiseObj_(c):this.fulfill_(c)}};D.prototype.resolveToNonPromiseObj_=function(c){var e=void 0;try{e=c.then}catch(kb){this.reject_(kb);return}"function"==
typeof e?this.settleSameAsThenable_(e,c):this.fulfill_(c)};D.prototype.reject_=function(c){this.settle_(2,c)};D.prototype.fulfill_=function(c){this.settle_(1,c)};D.prototype.settle_=function(c,e){if(0!=this.state_)throw Error("Cannot settle("+c+", "+e+"): Promise already settled in state"+this.state_);this.state_=c;this.result_=e;this.executeOnSettledCallbacks_()};D.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var c=0;c<this.onSettledCallbacks_.length;++c)Gb.asyncExecute(this.onSettledCallbacks_[c]);
this.onSettledCallbacks_=null}};var Gb=new e;D.prototype.settleSameAsPromise_=function(c){var e=this.createResolveAndReject_();c.callWhenSettled_(e.resolve,e.reject)};D.prototype.settleSameAsThenable_=function(c,e){var h=this.createResolveAndReject_();try{c.call(e,h.resolve,h.reject)}catch(ma){h.reject(ma)}};D.prototype.then=function(c,e){function h(c,e){return"function"==typeof c?function(e){try{q(c(e))}catch(Hb){Y(Hb)}}:e}var q,Y,wc=new D(function(c,e){q=c;Y=e});this.callWhenSettled_(h(c,q),h(e,
Y));return wc};D.prototype.catch=function(c){return this.then(void 0,c)};D.prototype.callWhenSettled_=function(c,e){function h(){switch(q.state_){case 1:c(q.result_);break;case 2:e(q.result_);break;default:throw Error("Unexpected state: "+q.state_);}}var q=this;null==this.onSettledCallbacks_?Gb.asyncExecute(h):this.onSettledCallbacks_.push(h)};D.resolve=h;D.reject=function(c){return new D(function(e,h){h(c)})};D.race=function(c){return new D(function(e,q){for(var D=$jscomp.makeIterator(c),Y=D.next();!Y.done;Y=
D.next())h(Y.value).callWhenSettled_(e,q)})};D.all=function(c){var e=$jscomp.makeIterator(c),q=e.next();return q.done?h([]):new D(function(c,D){function Y(e){return function(h){ma[e]=h;Na--;0==Na&&c(ma)}}var ma=[],Na=0;do ma.push(void 0),Na++,h(q.value).callWhenSettled_(Y(ma.length-1),D),q=e.next();while(!q.done)})};return D},"es6","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(c,e){this.$jscomp$symbol$id_=c;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:e})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function c(h){if(this instanceof c)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(h||"")+"_"+e++,h)}var e=0;return c}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.iterator;c||(c=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[c]&&$jscomp.defineProperty(Array.prototype,c,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.asyncIterator;c||(c=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(c){$jscomp.initSymbolIterator();c={next:c};c[$jscomp.global.Symbol.iterator]=function(){return this};return c};$jscomp.underscoreProtoCanBeSet=function(){var c={a:!0},e={};try{return e.__proto__=c,e.a}catch(h){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(c,e){c.__proto__=e;if(c.__proto__!==e)throw new TypeError(c+" is not extensible");return c}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(c){if(!(c instanceof Object))throw new TypeError("Iterator result "+c+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(c){this.yieldResult=c};$jscomp.generator.Context.prototype.throw_=function(c){this.abruptCompletion_={exception:c,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(c){this.abruptCompletion_={return:c};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(c){this.abruptCompletion_={jumpTo:c};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(c,e){this.nextAddress=e;return{value:c}};$jscomp.generator.Context.prototype.yieldAll=function(c,e){c=$jscomp.makeIterator(c);var h=c.next();$jscomp.generator.ensureIteratorResultIsObject_(h);if(h.done)this.yieldResult=h.value,this.nextAddress=e;else return this.yieldAllIterator_=c,this.yield(h.value,e)};
$jscomp.generator.Context.prototype.jumpTo=function(c){this.nextAddress=c};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(c,e){this.catchAddress_=c;void 0!=e&&(this.finallyAddress_=e)};$jscomp.generator.Context.prototype.setFinallyBlock=function(c){this.catchAddress_=0;this.finallyAddress_=c||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(c,e){this.nextAddress=c;this.catchAddress_=e||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(c){this.catchAddress_=c||0;c=this.abruptCompletion_.exception;this.abruptCompletion_=null;return c};$jscomp.generator.Context.prototype.enterFinallyBlock=function(c,e,h){h?this.finallyContexts_[h]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=c||0;this.finallyAddress_=e||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(c,e){e=this.finallyContexts_.splice(e||0)[0];if(e=this.abruptCompletion_=this.abruptCompletion_||e){if(e.isException)return this.jumpToErrorHandler_();void 0!=e.jumpTo&&this.finallyAddress_<e.jumpTo?(this.nextAddress=e.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=c};$jscomp.generator.Context.prototype.forIn=function(c){return new $jscomp.generator.Context.PropertyIterator(c)};
$jscomp.generator.Context.PropertyIterator=function(c){this.object_=c;this.properties_=[];for(var e in c)this.properties_.push(e);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var c=this.properties_.pop();if(c in this.object_)return c}return null};$jscomp.generator.Engine_=function(c){this.context_=new $jscomp.generator.Context;this.program_=c};
$jscomp.generator.Engine_.prototype.next_=function(c){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,c,this.context_.next_);this.context_.next_(c);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(c){this.context_.start_();var e=this.context_.yieldAllIterator_;if(e)return this.yieldAllStep_("return"in e?e["return"]:function(c){return{value:c,done:!0}},c,this.context_.return);this.context_.return(c);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(c){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],c,this.context_.next_);this.context_.throw_(c);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(c,e,h){try{var q=c.call(this.context_.yieldAllIterator_,e);$jscomp.generator.ensureIteratorResultIsObject_(q);if(!q.done)return this.context_.stop_(),q;var D=q.value}catch(Gb){return this.context_.yieldAllIterator_=null,this.context_.throw_(Gb),this.nextStep_()}this.context_.yieldAllIterator_=null;h.call(this.context_,D);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var c=this.program_(this.context_);if(c)return this.context_.stop_(),{value:c.value,done:!1}}catch(e){this.context_.yieldResult=void 0,this.context_.throw_(e)}this.context_.stop_();if(this.context_.abruptCompletion_){c=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(c.isException)throw c.exception;return{value:c.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(c){this.next=function(e){return c.next_(e)};this.throw=function(e){return c.throw_(e)};this.return=function(e){return c.return_(e)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(c,e){e=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(e));$jscomp.setPrototypeOf&&$jscomp.setPrototypeOf(e,c.prototype);return e};
$jscomp.asyncExecutePromiseGenerator=function(c){function e(e){return c.next(e)}function h(e){return c.throw(e)}return new Promise(function(q,D){function Gb(c){c.done?q(c.value):Promise.resolve(c.value).then(e,h).then(Gb,D)}Gb(c.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(c){return $jscomp.asyncExecutePromiseGenerator(c())};$jscomp.asyncExecutePromiseGeneratorProgram=function(c){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(c)))};
$jscomp.iteratorFromArray=function(c,e){$jscomp.initSymbolIterator();c instanceof String&&(c+="");var h=0,q={next:function(){if(h<c.length){var D=h++;return{value:e(D,c[D]),done:!1}}q.next=function(){return{done:!0,value:void 0}};return q.next()}};q[Symbol.iterator]=function(){return q};return q};
$jscomp.polyfill("Array.prototype.fill",function(c){return c?c:function(c,h,q){var e=this.length||0;0>h&&(h=Math.max(0,e+h));if(null==q||q>e)q=e;q=Number(q);0>q&&(q=Math.max(0,e+q));for(h=Number(h||0);h<q;h++)this[h]=c;return this}},"es6","es3");
function PEvs(c,e,h,q,D,Gb,wc){var Y,kb,ma,Se,ud,Vf,Na,Wb,Hb,da,lb,Ib=0,Xb=0,he,Oa=!1,xc=!1,Yb=0,mb=0,Zb=0,qb=0,vd,Oc,ie=3,$b=function(c){Na=c.target;for(Hb=Wb=0;Na;)Wb+=Na.offsetLeft-Na.scrollLeft,Hb+=Na.offsetTop-Na.scrollTop,Na=Na.offsetParent;Ib=(Oa?vd:c.pageX)-Wb-document.body.scrollLeft;Xb=(Oa?Oc:c.pageY)-Hb-document.body.scrollTop};this.getX=function(){return Ib};this.getY=function(){return Xb};this.setHysteresis=function(c){ie=c};var E=function(c){c.preventDefault();c.stopImmediatePropagation?
c.stopImmediatePropagation():c.stopPropagation()},je=function(c){$b(c);he=Ib;wa=Xb;T=!0;null!=ea&&(Se=(new Date).getTime());null!=na&&na(c)},I=function(c){T&&($b(c),T=!1,null!=rb&&rb(c),null!=ea&&(ud=(new Date).getTime(),Vf=ud-Se,300>Vf&&ea(c)))},Ja=function(c){$b(c);Math.abs(Ib-he)<ie&&Math.abs(Xb-wa)<ie||(wa=he=-9999,T?null!=Va&&Va(c):null!=nb&&nb(c),null!=ke&&Te())};this.touchDown=function(c){ma=!0;if(1<c.targetTouches.length)return Oa=!0,lb&&(mb=-1,E(c)),!1;Y=c.changedTouches;kb=Y[0];je(kb)};
this.touchUp=function(c){0==c.targetTouches.length&&(Oa=ma=!1);E(c);if(Oa||xc)return Oa||(xc=!1),!1;Y=c.changedTouches;kb=Y[0];I(kb)};this.touchMove=function(c){ma=!0;E(c);if(Oa)return lb&&(Y=c.targetTouches,vd=(Y[0].pageX+Y[1].pageX)/2,Oc=(Y[0].pageY+Y[1].pageY)/2,xc=!0,Zb=Y[0].pageX-Y[1].pageX,qb=Y[0].pageY-Y[1].pageY,Yb=Zb*Zb+qb*qb,$b(c),lb&&0<mb&&30<Math.abs(Yb-mb)&&lb(0<Yb-mb?1:-1),mb=Yb),!1;Y=c.changedTouches;kb=Y[0];Ja(kb)};this.pointUp=function(c){E(c);for(var e=0;e<xa.length;e++)if(xa[e].pointerId==
c.pointerId){xa.splice(e,1);break}0==xa.length&&(ma=Oa=!1);if(Oa||xc)return Oa||(xc=!1),!1;I(c);return!1};this.pointDown=function(c){E(c);xa.push(c);mb=-1;ma=!0;1<xa.length?Oa=!0:je(c);return!1};this.pointMove=function(c){E(c);for(var e=0;e<xa.length;e++)xa[e].pointerId==c.pointerId&&(xa[e]=c);if(Oa||!xc){if(Oa)return vd=(xa[0].pageX+xa[1].pageX)/2,Oc=(xa[0].pageY+xa[1].pageY)/2,$b(c),lb&&(xc=!0,Zb=xa[0].pageX-xa[1].pageX,qb=xa[0].pageY-xa[1].pageY,Yb=Zb*Zb+qb*qb,lb&&0<mb&&30<Math.abs(Yb-mb)&&lb(0<
Yb-mb?1:-1),mb=Yb),!1;Ja(c);return!1}};this.mouseDown=function(c){ma||(E(c),je(c))};this.clearDown=function(){T=!1};this.mouseUp=function(c){ma||(E(c),I(c))};this.useWheel=function(e){c.addEventListener("wheel",this.mouseWheel,!0);lb=e};this.mouseWheel=function(c){$b(c);var e=Math.max(-1,Math.min(1,-c.deltaY||-c.detail));E(c);lb&&lb(e)};this.mouseClick=function(c){E(c);T=!1};this.mouseMove=function(c){ma||(E(c),Ja(c))};this.mouseDragged=function(c){ma||(E(c),$b(c),null!=Va&&Va(c),null!=ke&&Te())};
var Te=function(){clearTimeout(da);da=setTimeout(function(){ke()},600)};var wa=he=Xb=Ib=0;var na=e;var rb=h;var nb=q;var Va=D;var ea=Gb;var ke=wc;var T=ma=!1;var xa=[];c.addEventListener("mousedown",this.mouseDown,!1);c.addEventListener("mouseup",this.mouseUp,!1);c.addEventListener("mousemove",this.mouseMove,!1);c.addEventListener("click",this.mouseClick,!1);c.addEventListener("touchstart",this.touchDown,!1);c.addEventListener("touchend",this.touchUp,!1);c.addEventListener("touchmove",this.touchMove,
!1);c.addEventListener("touchleave",this.touchUp,!1);c.addEventListener("touchcancel",this.touchUp,!1);c.addEventListener("contextmenu",function(c){c.preventDefault()},!1);c.style["touch-action"]="none";c.addEventListener("mouseout",function(c){T||(Xb=Ib=-1,null!=nb&&nb(c));T=!1})};var HAniS=new function(){function c(b){var a,g;wd=!0;if(b instanceof Array)for(f={},null!=oh&&(b=b.concat(oh)),a=0;a<b.length;a++){if(!(2>b[a].length)){var d=b[a].trim();if(0!=d.indexOf("#")){var c=d.indexOf("=");if(!(1>c)){var R=d.substr(0,c).trim().toLowerCase();f[R]=d.substr(c+1).trim()}}}}else f=b;Ue=!1;a=f.debug;null!=a&&("true"==a?(Wf=window.open("","HAniSDebugInfo","scrollbars=yes,width=400,height=200"),Ue=!0,fa("HAniS Version 4.44")):Ue=!1);a=f.no_initial_focus;null!=a&&"false"!=a||u.focus();
ob=!0;z(f.set_className,"f")&&(ob=!1);fa("Is type of param an array = "+(b instanceof Array));a=f.divalign;null!=a&&(le=a.trim(),u.align=le);z(f.prevent_shortcuts,"t")&&(Ve=!0);a=f.initial_message;null!=a&&(b=f.initial_message_style,null==b&&(b="background-color:red;top:10px;left:10px;height:100px;width:200px"),b="z-index:99;position:absolute;"+b,yc=p("div"),yc.setAttribute("style",b),yc.innerHTML=a,yc.addEventListener("click",function(){yc.style.visibility="hidden"},!1),yc.style.visibility="visible",
Wa.appendChild(yc),b=f.initial_message_timeout,null!=b&&("auto"==b?Xf=!0:(Xf=!1,b=parseInt(f.initial_message_timeout,10),2>b&&(b=2),setTimeout(function(){yc.style.visibility="hidden"},1E3*b))));xd=null;a=f.initial_enhancement;null!=a&&(xd=parseInt(a,10)-1);yd=!1;We="X = ";Xe=" Y = ";a=f.coordinates;null!=a&&(D(a),yd=!0,We="Lat = ",Xe=" Lon = ");d="green";c="white";R="12px Arial";var P=null,l=g=10,k=10;Yf=2;a=f.keyboard_propagate;null!=a&&z(a,"t")&&(Ye=!1);a=f.coordinates_display_style;null!=a&&(b=
a.split(","),d=b[0].trim(),c=b[1].trim(),R=b[2].trim(),3<b.length&&(We=b[3],Xe=b[4],Yf=parseInt(b[5],10),6<b.length&&(P=b[6].trim(),g=parseInt(b[7],10),l=parseInt(b[8],10),k=parseInt(b[9],10))));ph=new nb(d,c,R,P,g,l,k);Ze=Qc=null;null!=f.map_scale&&($e=ac=!0,b=f.map_scale.split(","),Qc=parseFloat(b[0]),Ze=1<b.length?parseFloat(b[1]):Qc);zd=yd?"km":" ";af=1;a=f.distance_unit;null!=a&&(zd=a.trim(),z(zd,"mi")&&(af=.621371192),z(zd,"nm")&&(af=.539956803),z(zd,"na")&&(af=.539956803));me=null;a=f.show_bearing;
null!=a&&(me=a.trim());a=f.divcan_style;null!=a&&a.trim();Zf="default";a=f.distance_cursor;null!=a&&(Zf=a.trim());bf="default";a=f.location_cursor;null!=a&&(bf=a.trim());cf="default";a=f.probe_cursor;null!=a&&(cf=a.trim());$f="default";a=f.mark_cursor;null!=a&&($f=a.trim());a=f.imagecan_style;null!=a&&(b=a.trim()+";position:absolute;top:0;left:0;",sb.setAttribute("style",b+"z-index:1;"),zc.setAttribute("style",b+"z-index:12;"));d="blue";c="white";R="12px Arial";P=null;k=l=g=10;ag=1;qh="white";a=f.distance_display_style;
null!=a&&(b=a.split(","),d=b[0].trim(),c=b[1].trim(),qh=5<=b.length?b[4].trim():c,R=b[2].trim(),ag=parseInt(b[3],10),5<b.length&&(P=b[5].trim(),g=parseInt(b[6],10),l=parseInt(b[7],10),k=parseInt(b[8],10)));Ni=new nb(d,c,R,P,g,l,k);d="black";c="white";R="12px Arial";P=null;k=l=g=10;a=f.probe_display_style;null!=a&&(b=a.split(","),d=b[0].trim(),c=b[1].trim(),R=b[2].trim(),3<b.length&&(P=b[3].trim(),g=parseInt(b[4],10),l=parseInt(b[5],10),k=parseInt(b[6],10)));Oi=new nb(d,c,R,P,g,l,k);rh="Undefined";
sh=!1;ne=0;a=f.probe_undefined;null!=a&&(b=a.split(","),rh=b[0].trim(),1<b.length&&(ne=parseInt(b[1],10)+1),2<b.length&&(sh=!0));bg=!1;f.probe_base_image&&(bg=!0);a=f.active_probe;null!=a&&(bc=!0);a=f.pause;null!=a&&(th=parseInt(a,10));a=f.auto_refresh;null!=a&&(cg=6E4*parseInt(a,10),Rc=setInterval("HAniS.reloadFOF();",cg),oe=!0);df=!1;uh="#FFFFFF80";a=f.show_hotspots;null!=a&&(b=a.split(","),z(b[0],"t")&&(df=!0),1<b.length&&(uh=b[1]));dg=!1;z(f.center_hotspots,"t")&&(dg=!0);Ad=!1;z(f.enable_smoothing,
"t")&&(Ad=!0);vh="low";a=f.smoothing_quality;null!=a&&(vh=a);ef=!0;z(f.check_image_size,"f")&&(ef=!1);wh=!1;a=f.sprites;if(null!=a){b=a.split(",");eg=new Image;fg=[];gg=[];cc=[];dc=[];if("row"==b[1].trim().toLowerCase())for(l=c=d=0,a=2;a<b.length;)for("row"==b[a].trim().toLowerCase()&&(d=0,c+=l,l=0,a+=1),g=parseInt(b[a],10),a+=1,R=parseInt(b[a],10),a+=1,P=parseInt(b[a],10),P>l&&(l=P),a+=1,k=0;k<g;k++)fg.push(d),gg.push(c),cc.push(R),dc.push(P),d+=R;else for(c=!1,a=1;a<b.length;)fg.push(parseInt(b[a],
10)),a+=1,gg.push(parseInt(b[a],10)),a+=1,a>=b.length?(d=0,c=!0):d=parseInt(b[a],10),0>d?(c=!0,cc.push(Math.abs(d)),a+=1,d=parseInt(b[a++],10),dc.push(Math.abs(d))):c?(cc.push(cc[cc.length-1]),dc.push(dc[dc.length-1])):(cc.push(parseInt(b[a],10)),a+=1,dc.push(parseInt(b[a],10)),a+=1);eg.onload=function(){wh=!0};eg.src=b[0]}a=f.overlay_labels;null!=a&&(ec=a.split(","));hg=null;a=f.auto_enhance_background;null!=a&&(hg=parseInt(a,10)-1);Sc=null;a=f.auto_enhance;if(null!=a)for(d=f.overlay_probe_table,
b=a.split(","),Sc=Array(b.length),a=0;a<b.length;a++)"x"==b[a].trim().toLowerCase()?Sc[a]=-1:Sc[a]=parseInt(b[a].trim(),10)-1,null==d&&(Ac[a]=Sc[a]);Tc=!1;tb=-1;a=f.overlay_enhance;null!=a&&(Tc=!0,tb=parseInt(a,10)-1);Bc=null;Bd=!0;a=f.overlay_allow_hoverzones;if(null!=a)for(b=a.split(","),Bc=Array(b.length),a=0;a<b.length;a++)if(Bc[a]=!0,z(b[a],"n")||z(b[a],"f"))Bc[a]=!1;V=Z=null;Uc=xh=!1;a=f.window_size;null!=a&&(b=a.split(","),"div"==b[0]?Uc=!0:(V=2*Math.floor(parseInt(b[0],10)/2),Z=2*Math.floor(parseInt(b[1],
10)/2)),xh=!0);ig=[];a=f.framenumber_index_values;null!=a&&(ig=a.split(","));Jb=[];a=f.use_for_all_frames;if(null!=a)for(b=a.split(","),a=0;a<b.length;a+=2)Jb[parseInt(b[a],10)]=parseInt(b[a+1],10)-1;pe=-1;a=f.skip_missing;null!=a&&(pe=parseInt(a,10));yh="#00000000";a=f.skip_missing_color;null!=a&&(yh=a);ff=null;a=f.overlay_spacer;if(null!=a)for(b=a.split(","),ff=Array(b.length),a=0;a<b.length;a++)ff[a]=parseInt(b[a],10);a=f.overlay_probe_table;if(null!=a)for(b=a.split(","),a=0;a<b.length;a++)"x"==
b[a].trim().toLowerCase()?Ac[a]=-1:Ac[a]=parseInt(b[a],10)-1;jg=[];a=f.overlay_ontop;if(null!=a)for(b=a.split(","),a=0;a<b.length;a++)jg[parseInt(b[a],10)-1]=!0;Vc=null;a=f.overlay_order;null==a&&(a=f.overlay_zorder);if(null!=a)for(b=a.split(","),Vc=Array(b.length),a=0;a<b.length;a++)Vc[parseInt(b[a],10)-1]=a;fc=null;a=f.overlay_links;if(null!=a)for(b=a.split(","),fc=Array(b.length),a=0;a<b.length;a++)fc[a]=parseInt(b[a],10);zh=[];K=null;a=f.overlay_slice;if(null!=a)for(b=a.split(","),a=0;a<b.length;a++)zh[parseInt(b[a],
10)-1]=!0;Ah=!0;z(f.slice_smoothing,"f")&&(Ah=!1);Cd=null;a=f.overlay_clear;if(null!=a)for(b=a.split(","),Cd=Array(b.length),a=0;a<b.length;a++)Cd[a]=b[a].trim().toLowerCase();Bh=!1;a=f.transparency;null!=a&&(b=a.split(","),1==b.length?Ch=Dh=Eh=parseInt(b[0],10):(Ch=parseInt(b[0],10),Dh=parseInt(b[1],10),Eh=parseInt(b[2],10)),Bh=!0);kg=!1;a=f.transparency_list;if(null!=a){b=a.split(",");Fh=[];for(a=0;a<b.length;a++)Fh[parseInt(b[a].trim(),10)-1]=!0;kg=!0}gf=null;a=f.overlay_transparent_amount;if(null!=
a)for(b=a.split(","),gf=Array(b.length),a=0;a<b.length;a++)gf[a]=parseFloat(b[a])/100;Wc=null;a=f.overlay_zoom;if(null!=ec&&null!=a)for(b=a.split(","),Wc=Array(b.length),a=0;a<b.length;a++)if(Wc[a]=1,z(b[a],"n")||z(b[a],"f"))Wc[a]=0;else if(z(b[a],"d")||z(b[a],"h"))Wc[a]=-1;ub=null;Gh=[];a=f.overlay_preserve_list;if(null!=ec&&null!=a)for(b=a.split(","),ub=Array(b.length),a=0;a<b.length;a++){ub[a]=!0;if(z(b[a],"n")||z(b[a],"f"))ub[a]=!1;if(z(b[a],"a")||z(b[a],"A"))Gh[a]=!0}ka=null;if(null!=ec&&null!=
ub)for(b=f.overlay_preserve.replace(/&/g,",&,").split(","),d=f.overlay_preserve_position,null!=d&&(d=d.split(",")),c=0,ka=Array(ub.length),a=R=0;a<ub.length;a++)if(ub[a]){ka[a]=[];P=0;do{ka[a][P]=[];for(g=0;4>g;g++)ka[a][P][g]=parseInt(b[R].trim(),10),R+=1;ka[a][P][2]=ka[a][P][2]-ka[a][P][0]+1;ka[a][P][3]=ka[a][P][3]-ka[a][P][1]+1;null!=d?(ka[a][P][4]=parseInt(d[c],10),ka[a][P][5]=parseInt(d[c+1],10),c+=2):(ka[a][P][4]=ka[a][P][0],ka[a][P][5]=ka[a][P][1]);R<b.length&&"&"==b[R].trim()?(R+=1,P+=1,g=
!0):g=!1}while(g)}hf=0;Hh=" ";Cc="white";qe="transparent";re="14pt arial";Ih=!1;a=f.times_label_style;null!=a&&(b=a.split(","),Cc=b[0].trim(),1<b.length&&(hf=Math.floor(60*parseFloat(b[1]))),1<b.length&&(hf="?"==b[1].trim()||"auto"==b[1].trim().toLowerCase()?-Math.floor((new Date).getTimezoneOffset()):Math.floor(60*parseFloat(b[1]))),2<b.length&&(Hh=b[2].trim()),3<b.length&&(qe=b[3].trim()),4<b.length&&(re=b[4].trim()),5<b.length&&-1!=b[5].trim().indexOf("t")&&(Ih=!0));0==Cc.indexOf("0x")&&(Cc="#"+
Cc.substring(2));0==qe.indexOf("0x")&&(qe="#"+qe.substring(2));Dd=parseInt(re,10);Pi=new nb("black","white",re,"black",20,5,5);Jh=!1;Jh=z(f.to_from_lock,"t")?!0:!1;a="black";g="white";l="14px arial";d=null;P=R=c=10;Kh=Lh=" ";lg=Ed=null;a=f.dirspd_display_style;null!=a&&(b=a.split(","),a=b[0].trim(),g=b[1].trim(),l=b[2].trim(),Kh=b[3],Lh=b[4],5<b.length&&(d=b[5].trim(),c=parseInt(b[6],10),R=parseInt(b[7],10),P=parseInt(b[8],10)),lg=new nb(a,g,l,d,c,R,P));d="black";c="white";R="14px arial";P=null;k=
l=g=10;a=f.tipbox_display_style;null!=a&&(b=a.split(","),d=b[0].trim(),c=b[1].trim(),R=b[2].trim(),3<b.length&&(P=b[3].trim(),g=parseInt(b[4],10),l=parseInt(b[5],10),k=parseInt(b[6],10)));Mh=new nb(d,c,R,P,g,l,k);Fd=null;ha=f.image_base;null!=ha?Fd=ha=ha.trim():ha=null!=f.image_only_base?f.image_only_base.trim():null;Nh=ha;a=f.overlay_base;null!=a&&(vb=a.trim());jf=!0;z(f.zip_only,"f")&&(jf=!1);Xc=!1;a=f.zip_filename;null!=a&&(Xc=!0,mg=a.trim());wd=!0;a=f.filenames;null==a&&(a=f.background_filenames);
null!=a&&Qi(a);a=f.basename;null!=a&&(d=f.base_starting_number,c=0,R=1,null!=d&&(b=d.split(","),c=parseInt(b[0],10),1<b.length&&(R=parseInt(b[1],10))),t=f.num_frames,null==t&&(t=f.num_images),t=parseInt(t,10),Ri(a,c,R));ng=!0;b=f.zip_static;if(z(b,"f")||z(b,"n"))ng=!1;og=!0;b=f.background_static;if(z(b,"f")||z(b,"n"))og=!1;a=f.overlay_filenames;null!=a&&Si(a);Pa=null;a=f.image_preserve;if(null!=a)for(b=a.split(","),Pa=[],a=0;a<b.length;a++)Pa[a]=parseInt(b[a].trim(),10),1<a%4&&(Pa[a]=Pa[a]-Pa[a-2]+
1);Oh=!1;z(f.keep_enhancement,"t")&&(Oh=!0);Ph=!0;z(f.keep_zoom,"f")&&(Ph=!1);Gd=pg=0;Qh=!1;a=f.hide_bottom;null!=a&&(b=a.split(","),pg=parseInt(b[0].trim(),10),1<b.length&&z(b[1],"t")&&(Qh=!0));Hd=qg=0;Rh=!1;a=f.hide_top;null!=a&&(b=a.split(","),qg=parseInt(b[0].trim(),10),1<b.length&&z(b[1],"t")&&(Rh=!0));Id=rg=0;Sh=!1;a=f.hide_left;null!=a&&(b=a.split(","),rg=parseInt(b[0].trim(),10),1<b.length&&z(b[1],"t")&&(Sh=!0));Jd=sg=0;Th=!1;a=f.hide_right;null!=a&&(b=a.split(","),sg=parseInt(b[0].trim(),
10),1<b.length&&z(b[1],"t")&&(Th=!0));Uh=!1;z(f.hide_background,"t")&&(Uh=!0);Vh="<div>";Wh=300;Xh=500;a=f.popup_style;null!=a&&(Vh='<div style="'+a+'">');a=f.popup_window_size;null!=a&&(b=a.split(","),Xh=b[0],Wh=b[1]);Yh=!1;a=f.wheel_frames;null!=a&&(Yh=!0,oa.useWheel(HAniS.wheel));Zh=Ha=!1;z(f.active_zoom,"t")&&(null==Ka&&(Ha=!0),oa.useWheel(HAniS.wheel));tg=!1;z(f.cycle_zoom,"t")&&(tg=!0);a=f.initial_zoom;null!=a&&(b=a.split(","),Dc="auto"!=b[0].toLowerCase()?parseFloat(b[0]):"auto",1<b.length?
(se=parseInt(b[1],10),$h=parseInt(b[2],10)):se=-1,ai=!0);Kd=1;Ld=!1;ra=null;a=f.zoom_scale;if(null!=a)if(b=a.split(","),1===b.length)z(a,"hi_res")?(Ld=!0,Kd=0):Kd=parseFloat(a);else{ra=Array(b.length);for(a=0;a<b.length;a++)ra[a]=parseFloat(b[a]);Ld=!0}Yc=9999999;a=f.maximum_zoom;null!=a&&(Yc=parseFloat(a));kf=!0;z(f.use_progress_bar,"f")&&(kf=!1);a=f.dwell;null!=a&&(b=a.split(","),Ia=parseInt(b[0].trim(),10),1<b.length&&(gc=parseInt(b[1].trim(),10),10>gc&&(gc=10),Zc=parseInt(b[2].trim(),10),ug=parseInt(b[3].trim(),
10)));a=f.rate;null!=a&&(b=a.split(","),Ia=Math.round(1E4/parseFloat(b[0].trim())),1<b.length&&(gc=Math.round(1E4/parseFloat(b[2].trim())),10>gc&&(gc=10),Zc=Math.round(1E4/parseFloat(b[1].trim()))));a=f.frame_times_template;null!=a&&(b=a.split(","));Md=27;a=f.mp4_quantization;null!=a&&(Md=parseInt(a,10),10>Md||51<Md)&&(Md=27);wb=null;a=f.times;if(null!=a){b=a.split(",");wb=Array(b.length);for(a=0;a<b.length;a++)wb[a]=parseInt(b[a].trim(),10);Y(wb)}a=f.extrap_times_filename;if(null!=a){wb=[];var h=
new XMLHttpRequest;h.open("get",a,!0);h.onload=function(){for(var a=h.responseText.split("\n"),b=0;b<a.length;b++){var d=a[b].split(" ");if(3==d.length){d[2].trim();var g=parseInt(d[0],10)-1;wb[g]=100*parseInt(d[2].substring(0,2),10)+parseInt(d[2].substring(3,5),10)+parseInt(d[2].substring(6,8),10)/30}}Y(wb)};h.send()}te=null;a=f.extrap_times_template;null!=a&&(te=RegExp(a));bi=["Click on target's initial position","Click on target's final position","Move pointer around or click here to select target"];
ci=10;z(f.extrap_prompts_position,"bot")&&(ci=9999);a=f.extrap_prompts;null!=a&&(bi=a.split(","));lf=["Click on first point to mark","Save points","Remove last point"];a=f.mark_prompts;null!=a&&(lf=a.split(","));mf=!0;z(f.mark_close,"f")&&(mf=!1);vg="12pt Arial";di="white";a=f.mark_prompts_style;null!=a&&(b=a.split(","),vg=b[0].trim(),1<b.length&&(di=b[1].trim()));ei=f.controls;fa("controls = "+f.controls);fa("bottom_controls = "+f.bottom_controls);$c=nf=hc=ic=xb=yb=of=Kb=null;null!=ei&&lb(ei,!0);
fi=f.bottom_controls;null!=fi&&lb(fi,!1);ad=!1;a=f.probe_table;null!=a&&q(a);b=f.enhance_filename;null==b&&(b=f.enhance_table);if(null!=b){fa("Reading enhancement table...");ad=!1;h=new XMLHttpRequest;zb=[];bd=[];pf=[];cd=[];jc=[];var S,Ec,m;bb=[];cb=[];db=[];ue=[];v=-1;gi=!0;var wg=!1,r,A,y,n,E,x,G,Q,H,B,J,I,C;h.onload=function(){for(var a=this.responseText.split("\n"),b=0;b<a.length;b++)if(!(2>a[b].length)){var d=a[b].replace(/\s+/g," ").trim(),g=d.indexOf("#");if(0!=g)if(0<g&&(d=d.substring(0,
g)),g=d.split(","),0==g[0].indexOf("*"))v++,zb[v]=Array(256),cd[v]=Array(256),bd[v]=Array(256),jc[v]=Array(256),bb[v]=Array(256),cb[v]=Array(256),db[v]=Array(256),ue[v]=Array(256),zb[v]=Array(256),pf[v]=1<g.length?g[1].trim():"None",S=" ",Ec="Value =",m=1,d=p("option"),d.innerHTML=g[0].substring(1),d.value=v,null!=Ea&&Ea.add(d);else{var c=d.indexOf("value");0>c&&(c=d.indexOf("probe"));wg=!1;B=J=0;0<c&&(g=d.substring(c+1),d=d.substring(0,c),c=g.indexOf("="),g=g.substring(c+1),g=g.split(","),1==g.length?
(Ec=g[0].trim(),m=-1,wg=!1):(B=parseFloat(g[0].trim()),J=parseFloat(g[1].trim()),2<g.length&&(m=parseInt(g[2],10)),3<g.length&&(S=Ti(g[3].trim())),4<g.length&&(Ec=g[4].trim()),wg=!0));d=d.split(" ");r=parseInt(d[0].trim(),10);A=parseInt(d[1].trim(),10);y=A-r;n=parseFloat(d[2].trim());E=parseFloat(d[3].trim());x=parseFloat(d[4].trim());G=parseFloat(d[5].trim());Q=parseFloat(d[6].trim());H=parseFloat(d[7].trim());I=C=255;9<d.length&&(I=parseFloat(d[8].trim()),C=parseFloat(d[9].trim()));for(d=r;d<=A;d++)0===
y?(bb[v][r]=n,cb[v][r]=x,db[v][r]=Q,ue[v][r]=I):(bb[v][d]=Math.round(n+(E-n)*(d-r)/y),cb[v][d]=Math.round(x+(G-x)*(d-r)/y),db[v][d]=Math.round(Q+(H-Q)*(d-r)/y),ue[v][d]=Math.round(I+(C-I)*(d-r)/y)),cd[v][d]=Ec,bd[v][d]=S,jc[v][d]=m,wg&&(zb[v][d]=B+(J-B)*(d-r)/y)}}-1!=tb&&w[tb].checked&&(Ea.disabled=!1);ad=!0;e()};h.open("get",b,!0);h.send()}else e()}function e(){var b=f.sprite_filenames;if(null!=b){var a=b.split(",");xg=0;pa=[];b=f.sprite_images_offset;dd=-1;null!=b&&(dd=parseInt(b,10)-1);for(b=0;b<
a.length;b++){pa[b]=new Image;pa[b].gotit=!1;pa[b].inx=b;pa[b].fromfile=!0;var g="/";0<a[b].indexOf("?")&&(g="?");pa[b].zoomme=0<a[b].indexOf(g+"zoom");pa[b].anim=0<a[b].indexOf(g+"animate");g=a[b].indexOf(g);0<g&&(a[b]=a[b].substring(0,g));pa[b].onload=function(){pa[this.inx].gotit=!0;xg++;xg==a.length&&h()};pa[b].src=a[b].trim()}}else h()}function h(){for(var b=Object.keys(f),a=0;a<b.length;a++)z(b[a],"hotspot")&&Xb("hotspot="+f[b[a]]);wd?HAniS.getFOF():(Fc=!0,Wb())}function q(b){var a=new XMLHttpRequest;
zb=[];pf=[];bd=[];var g=" ";cd=[];var d="Value=";jc=[];var c=1;ed=[];yg=[];bb=[];cb=[];db=[];var f,e=-1;v=-1;var l=0;a.onload=function(){for(var a=this.responseText.split("\n"),b=0;b<a.length;b++)if(!(2>a[b].length)){var la=a[b].replace(/\s+/g," ").trim().split(","),R=la[0].split(" ");if(0==R[0].indexOf("*"))v++,zb[v]=[],cd[v]=[],bd[v]=[],jc[v]=[],bb[v]=[],cb[v]=[],db[v]=[],yg[v]=[],ed[v]=[],e=-1,pf[v]=1<la.length?la[1].trim():"None",l=1;else if(0!=l){e++;var k=Array(3);zb[v][e]=parseFloat(R[0]);
bb[v][e]=parseInt(R[1].trim(),10);cb[v][e]=parseInt(R[2].trim(),10);db[v][e]=parseInt(R[3].trim(),10);0!=e&&(k[0]=bb[v][e]-bb[v][e-1],k[1]=cb[v][e]-cb[v][e-1],k[2]=db[v][e]-db[v][e-1],f=0,Math.abs(k[1])>Math.abs(k[f])&&(f=1),Math.abs(k[2])>Math.abs(k[f])&&(f=2),yg[v][e-1]=f,ed[v][e-1]=k,0==ed[v][e-1][f]&&(ed[v][e-1][f]=1));1<la.length&&(0==la[1].trim().indexOf('"')?(c=-1,la=la[1].trim(),d=la.substr(1,la.length-2),g=""):(c=parseInt(la[1],10),2<la.length&&(g=Ti(la[2].trim())),3<la.length&&(d=la[3].trim())));
cd[v][e]=d;jc[v][e]=c;bd[v][e]=g}}ad=!0};a.open("get",b,!0);a.send()}function D(b){b=b.split(",");var a=b[0].trim();"PS"===a?(kc=new mj,kc.init(b)):"CE"==a?(kc=new nj,kc.init(b)):"LCC"==a?(kc=new oj,kc.init(b)):(kc=null,zg=parseFloat(b[0]),Ag=parseFloat(b[1]),Ui=parseFloat(b[2]),Bg=parseFloat(b[3]),0<Ag&&0>Bg&&(Bg+=360));null==f.coordinates_display_style&&(We="Lat = ",Xe=" Lon = ");yd=!0}function Gb(b){var a=new XMLHttpRequest;a.onload=function(){c(this.responseText.split("\n"))};a.open("get",b+"?"+
Math.round(1E5*Math.random()),!0);a.send()}function wc(b){var a;if(null!=Cd){for(a=0;a<Cd.length;a++)-1!=Cd[a].indexOf(b)&&(w[a].checked=!1);for(a=0;a<Cd.length;a++)Ib(a)}}function Y(b){Cg=Array(b.length);for(var a=0;a<b.length;a++){var g=60*Math.floor(b[a]/100)+Math.floor(b[a])%100;0===a&&(lc=g);var d=g-lc;0>d&&(d=g+1440-lc);Cg[a]=d;fa("times s="+g+"  min="+Cg[a])}lc+=hf;1440<=lc&&(lc-=1440);0>lc&&(lc+=1440);fa("Starting minute = "+lc)}function kb(b,a){if(0!=b&&!fd)for(var g=0;g<b;g++)0==w[Qa[g].overlay].isGhost&&
(w[Qa[g].overlay].parentNode.style.visibility=a)}function ma(){var b,a,g,d,c;if(Dg){var f=new XMLHttpRequest;var e=0;L=[];f.onload=function(){var la=this.responseText.split("\n");fa("Processing FoF-substitute: "+hi);for(g=0;g<la.length;g++)if(!(2>la[g].length||0>la[g].indexOf(Vi))&&(L[e]=[],c=la[g].indexOf("overlay"),0<=c)){b=la[g].substring(c);c=b.indexOf("=");0>c&&fa("!! Cannot find a = sign in "+b);a=b.substring(c+1);b=a.trim();a=b.split(",");W=Math.max(W,a.length);fa("numOverlays reset in fof_substitute to "+
W);for(d=0;d<a.length;d++)L[e][d]=a[d].trim(),null!=ve&&Eg[d]?L[e][d]=(ve+L[e][d]).trim():null!=vb?L[e][d]=(vb+L[e][d]).trim():null!=ha&&(L[e][d]=(ha+L[e][d]).trim());e+=1}fa("Number of frames "+t+"... number of fof_sub frames = "+e);Se()};f.open("get",hi+"?"+Math.round(1E5*Math.random()),!0);f.send()}else Se()}function Se(){0!=Ab?kb(Ab,"visible"):0!=ii&&kb(ii,"hidden");Fc=!0;Wb()}function ud(b,a){Nd||(sb.height=a,sb.width=b,zc.height=a,zc.width=b,we.height=a,we.width=b,Od.height=a,Od.width=b,xe=
Od.getContext("2d"),V=2*Math.floor(b/2),Z=2*Math.floor(a/2),Uc&&(b=Pd*Z/V,a=Pd,b<gd&&(a=gd*V/Z,b=gd),sa=a,ta=b),qf=V/2-100,rf=Z/2-10,G=sa/V,H=ta/Z,ya=Math.floor(sa/B),za=Math.floor(ta/J),Gc=Hc=0,Uc&&(Hc=Math.round((sa-Pd)/2),Gc=Math.round((ta-gd)/2)),Wa.style.height=Z+"px",Wa.style.width=V+"px",Ic.style.height=Z+"px",Ic.style.width=V+"px",ye.style.height=Z+"px",ye.style.width=V+"px",Te(t,!1),ji&&(ji=!1,null!=ze&&ze()))}function Vf(){for(var b=0,a={},g=0;g<t;a={$jscomp$loop$prop$ii$2:a.$jscomp$loop$prop$ii$2},
g++){a.$jscomp$loop$prop$ii$2=g;var d=null==ha?Aa[g]:Aa[g].substring(Aa[g].lastIndexOf("/")+1);(d=ki.file(d))?d.async("arraybuffer").then(function(a){return function(d){d=new Blob([d]);Jc[a.$jscomp$loop$prop$ii$2]=URL.createObjectURL(d);b++;b>=t&&Na()}}(a),function(a){return function(){Jc[a.$jscomp$loop$prop$ii$2]=null;b++;b>=t&&Na()}}(a)):(Jc[a.$jscomp$loop$prop$ii$2]=null,b++,b>=t&&Na())}}function Na(){var b=0;if(0==W)Hb();else for(var a=0;a<t;a++){Kc[a]=[];for(var g={},d=0;d<W;g={$jscomp$loop$prop$ii$6:g.$jscomp$loop$prop$ii$6,
$jscomp$loop$prop$jj$7:g.$jscomp$loop$prop$jj$7},d++){g.$jscomp$loop$prop$ii$6=a;g.$jscomp$loop$prop$jj$7=d;var c=null==vb&&null==ha?L[a][d]:L[a][d].substring(L[a][d].lastIndexOf("/")+1);(c=ki.file(c))?c.async("arraybuffer").then(function(a){return function(d){d=new Blob([d]);Kc[a.$jscomp$loop$prop$ii$6][a.$jscomp$loop$prop$jj$7]=URL.createObjectURL(d);b++;b>=t*W&&Hb()}}(g),function(a){return function(){Kc[a.$jscomp$loop$prop$ii$6][a.$jscomp$loop$prop$jj$7]=null;b++;b>=t*W&&Hb()}}(g)):(Kc[a][d]=null,
b++,b>=t*W&&Hb())}}}function Wb(){if(Xc){var b=new XMLHttpRequest,a=null==Fd?mg:Fd+mg;ng||(a=a+"?"+Math.round(1E5*Math.random()));b.open("GET",a,!0);b.responseType="arraybuffer";Jc=[];Kc=[];b.addEventListener("progress",function(a){a.lengthComputable&&xa("Loading ZIP file",a.total,a.loaded)});b.onload=function(a){(new JSZip).loadAsync(this.response).then(function(a){ki=a;Vf()},function(){fa("Unable to read ZIP file: "+mg)})};b.send()}else Hb()}function Hb(){var b,a,g;void 0!=sf&&sf(!1);var d="?"+
Math.round(1E4*Math.random()),c=[];c[0]=Lb;null!=Bb&&(Bb.disabled=!0);null!=Mb&&(Mb.disabled=!0);for(b=1;b<t;b++)c[b]=b<=Lb?b-1:b;Ra=Array(t);mc=Sa=0;li=kf;Fg&&(La.max=t);Nd&&(Qd||Tc)&&(nc=[],Xa=[],hd=[],Gg=[],tf=[]);null!=Ea&&(Oh?null==xd&&(xd=Ea.value):Ea.selectedIndex=0);for(var f=0;f<t;f++){b=c[f];Nd&&(Qd||Tc)&&(nc[b]=p("canvas"),Xa[b]=p("canvas"));Ra[b]=new Image;Ra[b].gotit=!1;Ra[b].frameNum=b;Ra[b].onerror=function(){Sa++};Ra[b].onload=function(){Nd&&(ta=this.height,sa=this.width,gd=ta,Pd=
sa,Nd=!1,xh?Uc?HAniS.setWindowSize(u.offsetWidth,u.offsetHeight):ud(V,Z):ud(sa,ta),za=ta,ya=sa,ai&&("auto"==Dc&&(Dc=(G+H)/2,se=-1),za/=Dc,ya/=Dc,0>se&&(se=sa/2,$h=ta/2),N=Math.round(se-sa/2/Dc),M=Math.round($h-ta/2/Dc),B=J=Dc,1!=Dc&&(Ha=!1,HAniS.toggleZooming()),Gd=pg,Hd=qg,Jd=sg,Id=rg,Oc()));Xc&&null!=Jc[this.frameNum]&&URL.revokeObjectURL(Jc[this.frameNum]);if(0<uf&&!Rd){Hg.height=ta;Hg.width=sa;Ae=Hg.getContext("2d");Ae.clearRect(0,0,V,Z);for(var b=0;b<Ya.length;b++){for(var f=Ya[b].ctx.getImageData(0,
0,Ya[b].width,Ya[b].height).data,la=Ae.getImageData(Ya[b].xmin,Ya[b].ymin,Ya[b].width,Ya[b].height),e=3;e<f.length;e+=4)0!=f[e]&&(la.data[e]=b+1);Ae.putImageData(la,Ya[b].xmin,Ya[b].ymin)}Ha||(pb=!0);B==vf&&(pb=!0);Rd=!0}if(Fc){Fc=!1;C=sb.getContext("2d");C.imageSmoothingEnabled=Ad;C.imageSmoothingQuality=vh;C.fillStyle="blue";C.font="bold 20px Arial";k=zc.getContext("2d");k.imageSmoothingEnabled=Ad;Za=Array(t);Te(t,!0);wf&&!Ba?wa(na(Lb)):wa(na(m));if(0<W)for(F=Array(t),e=0;e<t;e++)for(g=c[e],F[g]=
Array(W),a=0;a<W;a++)if(void 0!=Jb[a+1]&&Jb[a+1]>=t&&(Jb[a+1]=t-1),void 0==Jb[a+1]||Jb[a+1]==g)F[g][a]=new Image,F[g][a].gotit=!1,F[g][a].frameNum=g,F[g][a].overlayNum=a,F[g][a].onerror=function(){Sa++},F[g][a].onload=function(){this.gotit=!0;var a=this.frameNum;Sa++;Pc();!ef||this.height==gd&&this.width==Pd?this.overlayNum==pe-1&&(Za[this.frameNum]=0):(this.gotit=!1,fa("Bad image size:"+this.src));if(Tc&&this.gotit&&this.overlayNum==tb)nc[a].height=this.height,nc[a].width=this.width,Be=nc[a].getContext("2d"),
Be.drawImage(this,0,0),Gg[a]=Be.getImageData(0,0,this.width,this.height).data,Xa[a].height=this.height,Xa[a].width=this.width,hd[a]=Xa[a].getContext("2d"),hd[a].drawImage(this,0,0),tf[a]=hd[a].getImageData(0,0,this.width,this.height),F[a][this.overlayNum]=null,F[a][this.overlayNum]=Xa[a],F[a][this.overlayNum].gotit=!0;else if(this.gotit&&w[this.overlayNum].hotspotIndex){var b=p("canvas");b.height=this.height;b.width=this.width;var d=b.getContext("2d");d.drawImage(this,0,0);var g=d.getImageData(0,
0,this.width,this.height).data,c=g.length;var e=this.overlayNum;var f;for(f=0;f<c;f+=4)if(0!=g[f]){0==eb&&(fb=[]);var la=g[f];var l=Math.floor(f/4/b.width);d=Math.floor(f/4%b.width);fb[eb]=new mb(d,l,"spritefn",la,"pan",null,null,e,a,null,null);eb++}}else if(this.gotit&&Bh&&(!kg||kg&&Fh[this.overlayNum])){b=p("canvas");b.height=this.height;b.width=this.width;d=b.getContext("2d");d.drawImage(this,0,0);l=d.getImageData(0,0,this.width,this.height);g=l.data;c=g.length;for(f=0;f<c;f+=4)g[f]===Ch&&g[f+
1]===Dh&&g[f+2]===Eh&&(g[f+3]=0);d.putImageData(l,0,0);F[a][this.overlayNum]=null;F[a][this.overlayNum]=b;F[a][this.overlayNum].gotit=!0}this.gotit&&jg[this.overlayNum]?(Ig.clearRect(0,0,V,Z),Ig.drawImage(F[a][this.overlayNum],0,0,V,Z)):this.gotit&&zh[this.overlayNum]&&null!=K&&(b=p("canvas"),b.height=ta,b.width=sa,8>K.length&&(K[4]=0,K[5]=0,K[6]=sa,K[7]=ta),d=b.getContext("2d"),d.imageSmoothingEnabled=Ah,d.drawImage(this,K[0],K[1],K[2],K[3],K[4],K[5],K[6],K[7]),F[a][this.overlayNum]=null,F[a][this.overlayNum]=
b,F[a][this.overlayNum].gotit=!0,null!=ub&&ub[this.overlayNum]&&(F[a][this.overlayNum].origImage=this));Xc&&null!=Kc[a][this.overlayNum]&&URL.revokeObjectURL(Kc[a][this.overlayNum]);if(void 0!=Jb[this.overlayNum+1]&&Jb[this.overlayNum+1]==a)for(b=0;b<t;b++)b!=a&&(F[b][this.overlayNum]=F[a][this.overlayNum],Sa++)},b=L[g][a],void 0==Ce||Ce[a]||(b+=d),F[g][a].src=Xc&&(jf||Kc[g][a])?Kc[g][a]:b,mc++;if(null!=id)for(oc=[],a=0;a<id.length;a++)oc[a]=new Image,oc[a].gotit=!1,oc[a].onerror=function(a){Sa++},
oc[a].onload=function(a){a.currentTarget.gotit=!0;Sa++;Pc()},oc[a].src=id[a],mc++;if(null!=Ta&&0<Ta.length)for(Ca=[],a=0;a<Ta.length;a++)if(void 0!=Ta[a])for(Ca[a]=[],g=0;g<Ta[a].length;g++)for(Ca[a][g]=[],e=0;e<t;e++)Wi(Ta[a][g],"/")?(b=L[e][a].lastIndexOf("/"),b=L[e][a].substring(0,b+1)+Ta[a][g]+L[e][a].substring(b+1),Ca[a][g][e]=new Image,Ca[a][g][e].gotit=!1,Ca[a][g][e].onerror=function(a){Sa++;Pc()},Ca[a][g][e].onload=function(a){a.currentTarget.gotit=!0;Sa++;Pc()},Ca[a][g][e].src=b,mc++):0===
e?(Ca[a][g][0]=new Image,Ca[a][g][0].gotit=!1,Ca[a][g][0].onerror=function(a){Sa++;Pc()},Ca[a][g][0].onload=function(a){a.currentTarget.gotit=!0;Sa++;Pc()},Ca[a][g][0].src=Ta[a][g],mc++):Ca[a][g][e]=Ca[a][g][0]}!ef&&0!=this.height&&0!=this.width||this.height==gd&&this.width==Pd?(this.gotit=!0,0==pe&&(Za[this.frameNum]=0)):(this.gotit=!1,fa("Image has invalid size:"+this.src));Qd&&this.gotit&&(e=this.frameNum,nc[e].height=this.height,nc[e].width=this.width,Be=nc[e].getContext("2d"),Be.drawImage(this,
0,0),Gg[e]=Be.getImageData(0,0,this.width,this.height).data,Xa[e].height=this.height,Xa[e].width=this.width,hd[e]=Xa[e].getContext("2d"),hd[e].drawImage(this,0,0),tf[e]=hd[e].getImageData(0,0,this.width,this.height),Ra[e]=null,Ra[e]=Xa[e],Ra[e].gotit=!0);Sa++;Pc();Ph||HAniS.resetZoom();jd=!0;Xi||(Xi=!0,Fa=!1,Yi());E(Ba)};var e=Aa[b];void 0!=Jb[0]&&(e=Jb[0],e>=t&&(e=t-1),e=Aa[e]);og||(e+=d);Ra[b].src=Xc&&(jf||Jc[b])?Jc[b]:e;mc++}kd=Nb=!1;ea()}function da(b,a,g,d,c,e){b.label_on=g;b.label_off=d;ob&&
(b.className=e);g=null;d=f[a+"_labels"];null==d&&(d=f[a+"_label"]);null!=d&&(d=d.split(","),b.label_on=d[0].trim(),1<d.length&&(b.label_off=d[1].trim()),2<d.length&&(g="width:"+d[2].trim()+"px;"));null!=c&&(b.title=c);b.innerHTML=b.label_on;c=a=d=f[a+"_style"];null!=d&&(d=d.split("&"),1<d.length&&(a=d[0],c=d[1]));b.style_on=(null!=g?g:"")+Lc+a;b.style_off=(null!=g?g:"")+Lc+c;null!=b.style_on&&1<b.style_on.length?b.setAttribute("style",b.style_on):(b.style_on=null,b.style_off=null)}function lb(b,a){Lc=
f.buttons_style;null==Lc&&(Lc="");var g=null,d=null;g=a?f.controls_tooltip:f.bottom_controls_tooltip;var c=b.split(",");if(null!=g){var e=g.split(",");e.length!=c.length&&(fa("!!! Number of tooltips must equal number of controls!"),e=g=null)}var k={};for(b=0;b<c.length;k={$jscomp$loop$prop$sfbounds$11:k.$jscomp$loop$prop$sfbounds$11},b++){var l=null!=g?e[b]:null;var h=c[b].trim();d=h.indexOf("/");if(0===d||0===b){0===d&&(h=h.substring(1));y=p("div");y.align=le;var q=f.controls_style;null!=q?y.setAttribute("style",
q):y.setAttribute("style","position:relative;padding:2px;width:100%;");a?(u.insertBefore(y,Wa),xf=y,xf.id=yf+"-top-controls"):(q=f.bottom_controls_style,null!=q&&y.setAttribute("style",q),u.appendChild(y),zf=y,zf.id=yf+"-bottom-controls")}"enhance"==h.trim()&&(Ea=p("select"),d=f.enhance_style,null!=d&&Ea.setAttribute("style",d),null!=l&&(Ea.title=l),d=p("option"),d.innerHTML=void 0==f.enhance_prompt?"Pick Enhancement":f.enhance_prompt,d.value=-1,Ea.add(d),Ea.addEventListener("change",HAniS.doEnhance,
!1),Qd=!Tc,Ea.disabled=Qd?!1:!0,y.appendChild(Ea));"custom"==h&&(of=p("button"),da(of,"custom","On","Off",l,"custom"),y.appendChild(of));"mp4"==h&&(Mb=p("button"),da(Mb,"mp4","Make MP4","Stop",l,"mp4"),Mb.addEventListener("click",HAniS.makeMP4,!1),y.appendChild(Mb));"anigif"==h&&(Bb=p("button"),da(Bb,"anigif","Make GIF","Stop",l,"anigif"),Bb.addEventListener("click",HAniS.makeAniGIF,!1),y.appendChild(Bb));"startstop"==h&&(Kb=p("button"),da(Kb,"startstop","Start","Stop",l,"startstop start"),Kb.addEventListener("click",
HAniS.toggleIsLooping,!1),y.appendChild(Kb));"looprock"==h&&(De=p("button"),da(De,"looprock","Rock","Loop",l,"looprock rock"),Ee=1,De.addEventListener("click",HAniS.toggleLoopRock,!1),y.appendChild(De),z(f.start_rocking,"t")&&HAniS.toggleLoopRock());"loophalt"==h&&(Fe=p("button"),da(Fe,"loophalt","Halt","Loop",l,"loophalt halt"),Cb=!1,Fe.addEventListener("click",HAniS.toggleLoopHalt,!1),y.appendChild(Fe));"extrap"==h&&(pc=p("button"),da(pc,"extrap","Enable Extrap","Disable Extrap",l,"extrap"),pc.addEventListener("click",
HAniS.toggleExtrap,!1),y.appendChild(pc));z(h,"location")&&(Sd=p("button"),da(Sd,"location","Show Loc","Hide Loc",l,"location"),0<h.indexOf("/on")?(I(Sd,!1,"location off"),Td=!0,Ma.push(u.style.cursor),u.style.cursor=bf):(Td=!1,u.style.cursor=Ma.pop()),Sd.addEventListener("click",function(){(Td=!Td)?(I(Sd,!1,"location off"),Ma.push(u.style.cursor),u.style.cursor=bf):(I(Sd,!0,"location on"),u.style.cursor=Ma.pop());ea()},!1),y.appendChild(Sd));"distance"==h&&(qc=p("button"),da(qc,"distance","Show dist",
"Hide dist",l,"distance"),ac=$e=!1,qc.addEventListener("click",function(){(ac=!ac)?(I(qc,!1,"distance off"),Ma.push(u.style.cursor),u.style.cursor=Zf):(I(qc,!0,"distance on"),u.style.cursor=Ma.pop())},!1),y.appendChild(qc));z(h,"probe")&&(Ud=p("button"),da(Ud,"probe","Show probe","Hide probe",l,"probe"),0<h.indexOf("/on")?(I(Ud,!1,"probe off"),bc=!0,Ma.push(u.style.cursor),u.style.cursor=cf):(bc=!1,u.style.cursor=Ma.pop()),Ud.addEventListener("click",function(){(bc=!bc)?(I(Ud,!1,"probe off"),Ma.push(u.style.cursor),
u.style.cursor=cf):(I(Ud,!0,"probe on"),u.style.cursor=Ma.pop())},!1),y.appendChild(Ud));"mark"==h&&(ld=p("button"),da(ld,"mark","Mark","Stop Mark",l,"mark"),Ge=!0,ld.addEventListener("click",function(){Db=!Db;ua=[];Db?(Vd=0,I(ld,!1,"mark off"),null!=Ka&&(Ka.disabled=!0),Ma.push(u.style.cursor),u.style.cursor=$f):(I(ld,!0,"mark on"),null!=Ka&&(Ka.disabled=!1),Vd=-1,u.style.cursor=Ma.pop());ea()},!1),Zi=new nb("black","white",vg,"black",20,5,5),mi=new nb("black","white",vg,"black",20,5,5),y.appendChild(ld));
"refresh"==h&&(nf=p("button"),da(nf,"refresh","Refresh",null,l,"refresh"),nf.addEventListener("click",HAniS.reloadFOF,!1),y.appendChild(nf));"restore"==h&&(Jg=p("button"),da(Jg,"restore","Restore",null,l,"restore"),Jg.addEventListener("click",function(a){for(a=0;a<w.length;a++)w[a].checked=w[a].restorableState;for(a=0;a<w.length;a++)Ib(a)},!1),y.appendChild(Jg));"setframe"==h&&(k.$jscomp$loop$prop$sfbounds$11=function(){var a=parseInt(La.value,10)-1;if(Af||Kg){for(var b=0;b<t;b++)Ja(b,0);Bf=0}else if(a!=
ni&&Lg){if(0==Bf){for(b=0;b<t;b++)b>a?Ja(b,0):Ja(b,-1);Bf=1}else{for(b=a+1;b<t;b++)Ja(b,-1);Bf=0;E(!0)}ni=a}},La=p("input"),ob&&(La.className="setframe"),La.type="range",La.min=1,La.max=100,La.value=1,Cf="Frame #*",null!=l&&(La.title=l),q=f.setframe_label,null!=q&&(Cf=q),He=p("span"),He.innerHTML=Cf.replace("*",1),d="display:block;vertical-align:middle;"+f.setframe_style,La.setAttribute("style",d),d=p("span"),d.setAttribute("style","display:inline-block;vertical-align:top;"),He.setAttribute("style",
"display:block;vertical-align:middle;"+f.setframe_label_style),d.appendChild(He),d.appendChild(La),y.appendChild(d),y.addEventListener("touchmove",function(a){a.stopPropagation()},!1),y.addEventListener("mousemove",function(a){a.stopPropagation()},!1),La.addEventListener("input",function(a){a.preventDefault();a.stopPropagation();E(!1);a=parseInt(La.value,10)-1;0<=Za[a]&&(wa(a),He.innerHTML=Cf.replace("*",m+1));T()},!1),Bf=0,ni=-1,La.addEventListener("pointerup",function(a){return function(b){b.stopPropagation();
a.$jscomp$loop$prop$sfbounds$11()}}(k),!1),La.addEventListener("mouseup",function(a){return function(b){b.stopPropagation();a.$jscomp$loop$prop$sfbounds$11()}}(k),!1),La.addEventListener("change",function(a){return function(b){b.stopPropagation();a.$jscomp$loop$prop$sfbounds$11()}}(k),!1),Fg=!0);"framelabel"==h&&(Ua=p("button"),ob&&(Ua.className="framelabel"),Ua.innerHTML="",null!=l&&(Ua.title=l),gb=null,q=f.frame_labels,null!=q&&(gb=q.split(","),Ua.innerHTML=gb[0]),d=Lc+f.framelabel_style,null!=
d&&Ua.setAttribute("style",d),d=f.framelabel_position,null!=d&&(d=d.split(","),Ua.style.position="absolute",Ua.style.left=u.offsetLeft+parseInt(d[0],10)+"px",Ua.style.top=u.offsetTop+parseInt(d[1],10)+"px"),y.appendChild(Ua));if("autorefresh"==h||"autorefresh/off"==h)null!=Rc&&clearInterval(Rc),$c=p("button"),da($c,"autorefresh","Disable Auto Refresh","Enable Auto Refresh",l,"autorefresh"),$c.addEventListener("click",HAniS.toggleAutoRefresh,!1),oe=!1,y.appendChild($c),"autorefresh"==h?HAniS.toggleAutoRefresh():
I($c,!1,"autotoggle off");"backward"==h&&(xb=p("button"),da(xb,"backward","<","<",l,"step back"),xb.addEventListener("click",function(){E(!1);rb(-1);T()},!1),y.appendChild(xb));"forward"==h&&(yb=p("button"),da(yb,"forward",">",">",l,"step forward"),yb.addEventListener("click",function(){E(!1);rb(1);T()},!1),y.appendChild(yb));if("step"==h){d=f.step_labels;var S=null!=d?d.split(","):["<",">"];xb=p("button");ob&&(xb.className="step back");xb.innerHTML=S[0];xb.addEventListener("click",function(){E(!1);
rb(-1);T()},!1);d=Lc+f.step_style;null!=d&&xb.setAttribute("style",d);null!=l&&(xb.title=l);y.appendChild(xb);yb=p("button");ob&&(yb.className="step forward");yb.innerHTML=S[1];yb.addEventListener("click",function(){E(!1);rb(1);T()},!1);null!=d&&yb.setAttribute("style",d);null!=l&&(yb.title=l);y.appendChild(yb)}"first"==h&&(Ob=p("button"),da(Ob,"first","|<","|<",l,"firstlast first"),Ob.addEventListener("click",function(){E(!1);wa(na(0));T()},!1),y.appendChild(Ob));"last"==h&&(Pb=p("button"),da(Pb,
"last",">|",">|",l,"firstlast last"),Pb.addEventListener("click",function(){E(!1);wa(na(t-1));T()},!1),y.appendChild(Pb));"firstlast"==h&&(d=f.firstlast_labels,S=null!=d?d.split(","):["<<",">>"],Ob=p("button"),ob&&(Ob.className="firstlast"),Ob.innerHTML=S[0],Ob.addEventListener("click",function(){E(!1);wa(na(0));T()},!1),d=Lc+f.firstlast_style,null!=d&&Ob.setAttribute("style",d),null!=l&&(Ob.title=l),y.appendChild(Ob),Pb=p("button"),ob&&(Pb.className="firstlast"),Pb.innerHTML=S[1],Pb.addEventListener("click",
function(){E(!1);wa(na(t-1));T()},!1),null!=d&&Pb.setAttribute("style",d),null!=l&&(Pb.title=l),y.appendChild(Pb));"setspeed"==h?(Qb=p("input"),ob&&(Qb.className="setspeed"),Qb.type="range",Qb.min=gc,Qb.max=Zc,Qb.value=Zc-Ia,null!=l&&(Qb.title=l),d="vertical-align:middle;"+f.setspeed_style,Qb.setAttribute("style",d),Qb.addEventListener("input",function(a){Ia=Zc-parseInt(Qb.value,10)+30;void 0!=Wd&&Wd(Ia);E(!0);T()},!1),y.appendChild(Qb)):"speed"==h&&(d=f.speed_labels,S=null!=d?d.split(","):["-","+"],
hc=p("button"),ob&&(hc.className="speed slower"),hc.innerHTML=S[0],hc.addEventListener("click",function(){Ia+=ug;ic.disabled=!1;Ia>Zc&&(Ia=Zc,hc.disabled=!0);void 0!=Wd&&Wd(Ia)},!1),d=Lc+f.speed_style,null!=d&&hc.setAttribute("style",d),null!=l&&(hc.title=l),y.appendChild(hc),ic=p("button"),ob&&(ic.className="speed faster"),ic.innerHTML=S[1],ic.addEventListener("click",function(){Ia-=ug;hc.disabled=!1;Ia<gc&&(Ia=gc,ic.disabled=!0);void 0!=Wd&&Wd(Ia)},!1),null!=d&&ic.setAttribute("style",d),null!=
l&&(ic.title=l),y.appendChild(ic));"zoom"==h&&(Ka=p("button"),da(Ka,"zoom","Zoom","Un-zoom",l,"zoom off"),Ka.addEventListener("click",HAniS.toggleZooming,!1),y.appendChild(Ka),Ha=!1);if("annotate"==h){Ie=p("button");da(Ie,"annotate","Annotate","Finished",l,"annotate");qa=p("div");qa.setAttribute("style","position:absolute;box-sizing:content-box;height:120px;width:180px;top:20px;left:20px;z-index:15;visibility:hidden;background-color:lightgray;border-width:6px;border-style:solid;border-color:magenta;border-radius:25px;padding:10px;font:normal normal normal 16px Arial;color:black;");
qa.title="Drag this box around.  Select attributes, then go onto the image and click & drag";md=nd=20;Df=Rb=!1;oi=3;pi=11;od=Je=0;r=[];qa.style["touch-action"]="none";var Ec=function(a){nd=a.clientX-od;md=a.clientY-Je;qa.style.top=md+"px";qa.style.left=nd+"px"};qa.addEventListener("mousedown",function(a){if(0!=a.clientX||0!=a.clientY)Df=!0,od=a.clientX-nd,Je=a.clientY-md},!1);qa.addEventListener("mouseup",function(a){Df=!1},!1);qa.addEventListener("mouseout",function(a){Df&&Ec(a)},!1);qa.addEventListener("mousemove",
function(a){Df&&Ec(a)},!1);window.PointerEvent?(qa.addEventListener("pointerdown",function(a){"mouse"!=a.pointerType&&(od=a.clientX-nd,Je=a.clientY-md)},!1),qa.addEventListener("pointermove",function(a){"mouse"!=a.pointerType&&(0==od&&(od=a.clientX,Je=a.clientY),Ec(a))},!1)):qa.addEventListener("touchmove",function(a){a=a.changedTouches[0];0==od&&(od=a.clientX,Je=a.clientY);Ec(a)},!1);Ie.addEventListener("click",function(){if(Rb=!Rb){r=[];nd=u.offsetLeft;md=u.offsetTop;var a=f.annotate_position;null!=
a&&(a=a.split(","),nd+=parseInt(a[0],10),md+=parseInt(a[1],10));qa.style.top=md+"px";qa.style.left=nd+"px";qa.style.visibility="visible";I(Ie,!1,"annotate off");$i=Ha;Ha=!1;null!=Ka&&(Ka.disabled=!0)}else qa.style.visibility="hidden",I(Ie,!0,"annotate on"),Ha=$i,null!=Ka&&(Ka.disabled=!1);ea()},!0);Ke=qi("Color Black White Red Green Blue Yellow Orange Cyan Magenta".split(" "),"black black white red green blue yellow orange cyan magenta".split(" "),function(a){});Mc=qi("Width 1 2 3 4 5 6 7 8 10 12 14 16 18 20 24 28 32 36 38".split(" "),
[1,1,2,3,4,5,6,7,8,10,12,14,16,18,20,24,28,32,36,38],function(a){6==Le.selectedIndex?pi=Mc.selectedIndex:oi=Mc.selectedIndex});Mc.title="Select width or font size";Le=qi("Type Arrow Circle Box Polygon Draw Text Line".split(" "),[-1,0,1,2,3,4,5,6],function(a){6==Le.selectedIndex?(Sb.focus(),Sb.select(),Mc.selectedIndex=pi):Mc.selectedIndex=oi;0==Ke.selectedIndex&&(Ke.selectedIndex=2)});d=p("button");d.style.width="70px";d.style.margin="5px";d.innerHTML="Erase";d.title="Erase last item";d.addEventListener("click",
function(){0<r.length&&(r.pop(),ea())},!1);Sb=p("input");Sb.type="text";Sb.style.width="150px";Sb.style.margin="5px";Sb.title="Enter your text here, then click where you want it";Sb.value="Text input";S=f.annotate_defaults;null!=S&&(S=S.split(","),Le.selectedIndex=parseInt(S[0],10),1<S.length&&(Ke.selectedIndex=parseInt(S[1],10)),2<S.length&&(Mc.selectedIndex=parseInt(S[2],10)),3<S.length&&(Sb.value=S[3].trim()));S=p("div");S.innerHTML="Annotation Tools";var v=p("div");v.appendChild(Le);v.appendChild(Ke);
var n=p("div");n.appendChild(Mc);n.appendChild(d);d=p("div");d.appendChild(Sb);qa.appendChild(S);qa.appendChild(v);qa.appendChild(n);qa.appendChild(d);y.appendChild(Ie);u.appendChild(qa)}"saveall"==h&&(Mg=p("button"),da(Mg,"saveall","SaveAll","SaveAll",l,"saveall"),ri=f.saveall_prompt,rc=f.saveall_filename,d=f.saveall_list,si=null==d?["0"]:d.split(","),Mg.addEventListener("click",function(){for(var a=0;a<si.length;a++)for(var b=parseInt(si[a],10),d=0;d<Aa.length;d++){0===d&&null!=ri&&(rc=window.prompt(ri,
rc),null!=rc&&1>rc.length&&(rc=null));var g=null==rc?"":-1!=rc.indexOf("#")?rc.replace("#",d.toString()):rc+d;var c=document.createElement("a");c.href=0==b?Aa[d]:L[d][b-1];c.download=g;c.click()}},!1),y.appendChild(Mg));if("capture"==h){Ng=p("button");da(Ng,"capture","Capture","Capture",l,"capture");var A=f.capture_prompt;Og=f.capture_filename;null==Og&&(Og="haimage.png");Ng.addEventListener("click",function(){var a=Og;if(null!=A&&(a=window.prompt(A,a),null==a))return;var b=p("canvas");b.height=sb.height;
b.width=sb.width;var d=b.getContext("2d");Ge=!1;ea();d.drawImage(sb,0,0);d.drawImage(zc,0,0);Ge=!0;b.toBlob(function(b){var d=URL.createObjectURL(b),g=document.createElement("a");g.href=d;g.download=a;g.click();setTimeout(function(){URL.revokeObjectURL(b)},3E4)})},!1);y.appendChild(Ng)}"show"==h&&(Pg=p("button"),da(Pg,"show","Show","Show",l,"show"),Qg=f.show_prompt,aj=f.show_image_file,null==Qg&&(Qg="Right-click to save or copy the image<br> <font size='-1'>(to save in some browsers, you may need to first 'Open in New Tab')</font> <p>"),
Pg.addEventListener("click",function(){if(aj)window.open(Aa[m]);else{var a=sb.toDataURL("image/png;base64;");var b=window.open();b.document.write(Qg+"<img src="+a+"></img>")}},!1),y.appendChild(Pg));"toggle"==h&&(Za=[],d=f.toggle_size,null!=d?(d=d.split(","),Xd=parseInt(d[0],10),Ef=parseInt(d[1],10),Ff=parseInt(d[2],10)):(Ef=Xd=10,Ff=3),ti="red",ui="blue",vi="orange",wi=!1,z(f.toggle_layout_width,"t")&&(wi=!0),d=f.toggle_colors,null!=d&&(d=d.split(","),ui=d[0].trim(),ti=d[1].trim(),vi=d[2].trim()),
Eb=p("div"),Eb.setAttribute("style","position:relative;border:0px;margin:0px;padding:0px;-webkit-user-select:none; -moz-user-select:none; -ms-user-select:none; user-select:none; -webkit-tap-heightlight-color:transparent;"),Eb.style.backgroundColor=y.style.backgroundColor,Eb.align=le,Rg=new PEvs(Eb,HAniS.togdown,HAniS.togup,null,HAniS.togdown,null,null),Rg.setHysteresis(0),pd=p("canvas"),pd.height=2*Ef,Sg=pd.getContext("2d"),Eb.appendChild(pd),a?u.insertBefore(Eb,Wa):u.appendChild(Eb),d=f.toggle_onoff,
Gf=null,null!=d&&(Gf=d.split(",")),Tg=!0,null!=l&&(Eb.title=l));if("overlay"==h||z(h,"menu")){0==Ga&&(w=[]);S=f.overlay_tooltip;d=null;null!=S&&(d=S.split(","));S=f.overlay_radio;v=null;null!=S&&(v=S.split(","));var B=f.overlay_menu_links;n=null;null!=B&&(n=B.split(","));var D=f.overlay_labels_color;B=null;null!=D&&(B=D.split(","));var G=f.overlay_smoothing;D=null;null!=G&&(D=G.split(","));Hf=[];var H=G=fd=!1;z(h,"menu")&&(fd=!0,0<h.indexOf("/on")&&(G=!0),0<h.indexOf("/always")&&(H=!0));0==Ga&&(Ce=
[]);var x=f.overlay_caching;h=null;null==x&&(x=f.overlay_static);null!=x&&(h=x.split(","));var J=!0;null!=f.overlay_nonewdiv&&(J=!1);Ga++;for(x=0;x<ec.length;x++){var Q=ec[x].trim();Hf[x]=Ad;null!=D&&(z(D[x],"t")||z(D[x],"y")?Hf[x]=!0:Hf[x]=!1);if(0==x||0==Q.indexOf("/")){0==Q.indexOf("/")&&(Q=Q.substr(1));if(fd){hb[Ga]=p("div");hb[Ga].dropalways=H;var C="menu"+Ga+"_labels_style";hb[Ga].setAttribute("style","text-align:left;display:block;position:absolute;border-style:solid;border-width:2px;background:#ffffff;z-index:99;visibility:"+
(G||H?"visible":"hidden")+";"+(void 0==f[C]?f.overlay_labels_style:f[C]));Ug++}else J?(Tb=p("div"),Ug++,Tb.align="center",a?u.insertBefore(Tb,Wa):u.appendChild(Tb)):(Tb=p("span"),y.appendChild(Tb));q=f.overlay_labels_style;fd||null==q||Tb.setAttribute("style",q)}if(null==n||null!=n&&n[x]==Ga){C=!1;-1!=Q.indexOf("<a href=")&&(C=!0);var F=!1,K=!1,N=!1,M=!1;q=Q.length;C||(0<Q.indexOf("/on")&&Q.indexOf("/on")==q-3&&(F=!0),0<Q.indexOf("/always")&&Q.indexOf("/always")==q-7&&(K=F=!0),0<Q.indexOf("/hidden")&&
(N=!0),0<Q.indexOf("/hotspots")&&(M=!0),-1!=Q.indexOf("/")&&(Q=Q.substr(0,Q.indexOf("/"))));null!=h?z(h[x],"y")||z(h[x],"t")?Ce[x]=!0:Ce[x]=!1:Ce[x]=!0;w[x]=p("input");w[x].type="checkbox";w[x].value=Q;w[x].id=yf+Q;w[x].showMe=!(K&N)&!M;var O="vertical-align:middle;";q=f.checkbox_style;null!=q&&(O+=q);w[x].setAttribute("style",O);w[x].checked=F;w[x].restorableState=F;w[x].name=0;w[x].hotspotIndex=M;null!=Ea&&x==tb&&w[x].checked&&(Ea.disabled=!1);null!=Bc&&!Bc[x]&&F&&(Bd=!1);w[x].addEventListener("click",
HAniS.overClick,!1);null!=S&&(q=v[x].indexOf("/"),-1!=q&&(w[x].name=v[x].substr(q+1).trim()),z(v[x],"t")&&(w[x].type="radio",-1==q&&(w[x].name="all")));w[x].isGhost=!0;K||N||(null!=d&&(w[x].title=d[x]),K=p("label"),K.htmlFor=yf+Q,null!=d&&(K.title=d[x]),K.innerHTML=Q,K.name=w[x].name,Q="vertical-align:middle;",null!=B&&(Q=Q+"color:"+B[x]+";"),K.setAttribute("style",Q),Q=p("span"),C||Q.appendChild(w[x]),Q.appendChild(K),fd?(Q.setAttribute("style","display:block;margin-right:5px;"),hb[Ga].appendChild(Q)):
(C="10",null!=ff&&(C=10+ff[x]),Q.setAttribute("style","margin-left:"+C+"px;"),Tb.appendChild(Q)),w[x].isGhost=!1)}}fd&&(qd[Ga]=p("button"),da(qd[Ga],"menu"+Ga,"Show Overlay Menu","Hide Menu",l,"menu off"),qd[Ga].menuInx=Ga,qd[Ga].addEventListener("click",function(a){if("hidden"===hb[this.menuInx].style.visibility){for(a=1;a<hb.length;a++)hb[a].dropalways||"visible"!=hb[a].style.visibility||(hb[qd[a].menuInx].style.visibility="hidden",I(qd[a],!0,"menu off"));hb[this.menuInx].style.visibility="visible";
I(this,!1,"menu on")}else hb[this.menuInx].style.visibility="hidden",I(this,!0,"menu off")},!1),hb[Ga].dropalways||y.appendChild(qd[Ga]),u.insertBefore(hb[Ga],Wa));if(null==fc)for(fc=Array(ec.length),x=0;x<ec.length;x++)fc[x]=0;else for(x=0;x<ec.length;x++)Ib(x)}}Ba=!0;wf=null;q=f.start_looping;null!=q&&(d=q.split(","),z(d[0],"f")&&(Ba=!1),1<d.length&&(Lb=parseInt(d[1],10)-1,isNaN(Lb)&&(Lb=0),m=Lb),2<d.length&&(z(d[2],"t")&&(wf=!0),z(d[2],"f")&&(wf=!1)));E(Ba)}function Ib(b){var a;if(0>fc[b]){var g=
!1;for(a=0;a<ec.length;a++)fc[a]!=-fc[b]||g||(g=w[a].checked);w[b].checked=g}}function Xb(b){0==eb&&(fb=[]);b=b.substr(b.indexOf("=")+1).trim().split(",");var a=b[4].trim(),g=b[4].indexOf("/"),d=b[4].indexOf("?"),c=-1,e=-1;-1!=g&&(c=parseInt(b[4].substring(g+1),10)-1,a=a.substring(0,g));-1!=d&&(e=parseInt(b[4].substring(d+1),10)-1,d<g||-1==g)&&(a=a.substring(0,d));fb[eb]=new mb(parseInt(b[0].trim(),10),parseInt(b[1].trim(),10),b[2].trim(),b[3].trim(),a.toLowerCase(),b[5].trim().toLowerCase(),b[6].trim(),
c,e,8<=b.length?b[7].trim():null,9==b.length?b[8].trim():null);eb+=1}function he(b){0==uf&&(Ya=[],va=null);var a=b.substr(b.indexOf("=")+1).trim().split("(");b=a[0].split(",");var g=b[0].trim();0==g.indexOf("0x")&&(g="#"+g.substring(2));Ya[uf]=new xc(g,b[1].trim(),b[2].trim(),b[3].trim(),a[1].trim());uf+=1}function Oa(b){0==Ab&&(Qa=[]);b=b.substr(b.indexOf("=")+1).trim().split(",");Qa[Ab]=new Yb(parseInt(b[0],10)-1,parseInt(b[1],16),b[2].trim(),b[3].trim(),5==b.length?b[4].trim():"Click for details");
Ab+=1}function xc(b,a,g,d,c){this.color=b;this.alpha=1;7<this.color.length&&(this.alpha=parseInt(this.color.substring(7),16)/255,this.color=this.color.substring(0,7),.1>this.alpha&&(this.alpha=.1));this.action=a;this.value=g;this.tip=d;this.poly=c;b=c.split(",");this.xy=[];this.ymin=this.xmin=9999;for(a=this.ymax=this.xmax=0;a<b.length;a++)this.xy[a]=parseInt(b[a].trim(),10),0==a%2?(this.xy[a]<this.xmin&&(this.xmin=this.xy[a]),this.xy[a]>this.xmax&&(this.xmax=this.xy[a])):(this.xy[a]<this.ymin&&(this.ymin=
this.xy[a]),this.xy[a]>this.ymax&&(this.ymax=this.xy[a]));this.height=this.ymax-this.ymin+1;this.width=this.xmax-this.xmin+1;this.can=p("canvas");this.can.height=this.height;this.can.width=this.width;this.ctx=this.can.getContext("2d");this.ctx.imageSmoothingEnabled=!1;this.ctx.fillStyle=this.color;this.ctx.globalAlpha=this.alpha;this.ctx.beginPath();this.ctx.moveTo(this.xy[0]-this.xmin,this.xy[1]-this.ymin);for(a=2;a<this.xy.length;a+=2)this.ctx.lineTo(this.xy[a]-this.xmin,this.xy[a+1]-this.ymin);
this.ctx.closePath();this.ctx.fill()}function Yb(b,a,g,d,c){this.overlay=b;this.color=a;this.action=g;this.value=d;this.tip=c}function mb(b,a,g,d,c,e,f,l,k,h,q){this.x0=b;this.y0=a;this.icon=null;this.isIcon=!1;if("icon"==g)this.icon=new Image,this.icon.hotspot=this,Vg=!0,this.icon.onload=function(a){this.gotit=!0;this.hotspot.x1=this.hotspot.x0+this.width;this.hotspot.y1=this.hotspot.y0+this.height;this.hotspot.width=this.width;this.hotspot.height=this.height;this.hotspot.w2=this.width/2;this.hotspot.h2=
this.height/2;this.hotspot.isIcon=!0;this.hotspot.origX=0;this.hotspot.origY=0},this.y1=this.x1=-1,this.zoomme=this.fromfile=this.anim=!1,this.icon.gotit=!1,this.icon.src=d.trim();else if("sprite"==g||"spritefn"===g){this.x0=b;this.y0=a;this.inx=parseInt(d,10)-1;Me=!1;wh?null!=pa&&(-1!=dd?this.inx>=dd&&this.inx<=dd+pa.length&&(Me=!0):"spritefn"===g&&(Me=!0)):Me=!0;if(Me){-1!=dd&&(this.inx-=dd);if(this.inx>=pa.length)return null;this.x1=pa[this.inx].width+b;this.y1=pa[this.inx].height+a;this.width=
pa[this.inx].width;this.height=pa[this.inx].height;this.w2=this.width/2;this.h2=this.height/2;this.origY=this.origX=0;this.icon=pa[this.inx].cloneNode();this.anim=pa[this.inx].anim;this.fromfile=pa[this.inx].fromfile;this.zoomme=pa[this.inx].zoomme;this.anim&&(this.icon.setAttribute("style","position:absolute;top:0px;left:0px;visibility:hidden;"),Ic.appendChild(this.icon))}else this.x1=cc[this.inx]+b,this.y1=dc[this.inx]+a,this.width=cc[this.inx],this.height=dc[this.inx],this.w2=cc[this.inx]/2,this.h2=
dc[this.inx]/2,this.origX=fg[this.inx],this.origY=gg[this.inx],this.icon=eg,this.zoomme=this.fromfile=this.anim=!1;Vg=this.isIcon=!0;this.icon.gotit=!0}else this.width=parseInt(g,10),this.height=parseInt(d,10),this.w2=this.width/2,this.h2=this.height/2,dg&&(this.x0=b-this.w2,this.y0=a-this.h2),this.x1=this.width+this.x0,this.y1=this.height+this.y0;this.pan=c;this.isPan=!1;"pan"===this.pan&&(this.isPan=!0);this.action=e;this.value=f;this.overlay=l;this.frame=k;this.tip=h;this.target=q}function Zb(){if(Yd&&
!Ld){ba=-1;for(var b=0;b<ra.length;b++)B>=ra[b]&&(ba=b)}}function qb(){null!=kc?Da=kc.toLatLon(ia-Hc,ja-Gc):null!=zg?(Da[0]=zg+(Ui-zg)*(ja-Gc)/gd,Da[1]=Ag+(Bg-Ag)*(ia-Hc)/Pd):(Da[0]=Math.round(ia-Hc),Da[1]=Math.round(ja-Gc))}function vd(b,a){"popup"==b.action?(null!=Wg&&Wg.close(),Wg=window.open("","HAniSPopup","scrollbars=yes,width="+Xh+",height="+Wh),Wg.document.write(Vh+b.value+"</div>")):"link"==b.action?(a=b.value,qb(),a=a.replace("%LATITUDE%",Da[0].toFixed(4)),a=a.replace("%LONGITUDE%",Da[1].toFixed(4)),
a=a.replace("%FRAMENUMBER%",m+1),a=a.replace("%FRAMENUMBERINDEX%",ig[m]),window.open(a,b.target?b.target:"_blank","")):"fof"==b.action&&(ha=Nh,HAniS.resetZoom(),HAniS.newFOF(b.value,!0),wc(a))}function Oc(){if(!Uc){var b=Sh?Id/B:0;N+b<Id&&(N=Id-b);b=Th?Jd/B:0;N+ya-b>sa-Jd&&(N=sa-ya+b-Jd);b=Rh?Hd/J:0;M+b<Hd&&(M=Hd-b);b=Qh?Gd/J:0;M+za-b>ta-Gd&&(M=ta-za-Gd+b);M=Math.round(M);N=Math.round(N)}}function ie(b){var a=!1;b?Ld?(ba--,0>ba?a=!0:(B=ra[ba],J=ra[ba])):(B-=.1*Kd/G,J-=.1*Kd/H):Ld?(ba++,ba>=ra.length?
(ba--,tg&&(a=!0)):(B=ra[ba],J=ra[ba])):(!tg||B!==Yc&&J!==Yc||(a=!0),B+=.1*Kd/G,J+=.1*Kd/H,B>Yc&&(B=Yc),J>Yc&&(J=Yc));a||B<=vf||J<=If?(B=vf,J=If,ba=-1,ia=n,ja=A,M=N=0,za=ta,ya=sa,Id=Jd=Hd=Gd=0,Rd&&(pb=!0)):(Gd=pg,Hd=qg,Jd=sg,Id=rg,N=ia-n/B,M=ja-A/J,za=Math.floor(ta/J),ya=Math.floor(sa/B),Oc(),Rd&&(pb=!1));Zb();void 0!=Zd&&Zd(["zoom",B,J,ia,ja,n,A,N,M,ya,za])}function $b(){Jf=0;Ub=Array(2);Fb=Array(2);$d=Array(2);$a=0;Ed=null;wa(na(0))}function E(b){Fa=!b;HAniS.toggleIsLooping()}function je(b,a,g,d,
c,e,f,l){Od.height=c;Od.width=d;xe.clearRect(0,0,d,c);xe.imageSmoothingEnabled=Ad;C.imageSmoothingEnabled=Ad;xe.drawImage(b,a,g,d,c,0,0,d,c);xi=xe.getImageData(0,0,d,c);rd=xi.data;Xg=bb[l];Yg=cb[l];Zg=db[l];$g=ue[l];bj=4*d*c;for(sc=0;sc<bj;sc+=4)ib=rd[sc],ib===rd[sc+1]&&ib===rd[sc+2]&&(rd[sc]=Xg[ib],rd[sc+1]=Yg[ib],rd[sc+2]=Zg[ib],rd[sc+3]=$g[ib]);xe.putImageData(xi,0,0);C.drawImage(Od,e,f,V,Z)}function I(b,a,c){null!=b&&(a?(null!=b.style_on&&b.setAttribute("style",b.style_on),b.innerHTML=b.label_on):
(null!=b.style_off&&b.setAttribute("style",b.style_off),b.innerHTML=b.label_off),ob&&(b.className=c))}function Ja(b,a){if(!(b>=t)&&(-2==Za[b]&&(a=-2),Za[b]=a,Fg&&1==a&&(La.value=b+1,He.innerHTML=Cf.replace("*",b+1)),Tg)){b=yi+b*(Xd+Ff);var c=vi;0==a?c=ui:-1==a?c=ti:-2==a&&(c=yh);Sg.fillStyle=c;Sg.fillRect(b,Ef/2,Xd,Ef)}}function Te(b,a){Tg&&(pd.width=wi?parseInt(u.style.width,10):V,Sg.clearRect(0,0,pd.width,pd.height),yi=pd.width/2-b*(Xd+Ff)/2);for(var c=0;c<b;c++)a?-1!=pe?Ja(c,-2):null!=Gf&&"n"==
Gf[c].toLowerCase().trim()?Ja(c,-1):Ja(c,0):Ja(c,Za[c])}function wa(b){Ja(m,0);m=b;Ja(m,1);null!=Ua&&null!=gb&&null!=gb[m]&&(Ua.innerHTML=gb[m]);void 0!=Kf&&Kf(m)}function na(b){b>=t&&(b=t-1);if(0<=Za[b])return b;var a=-1,c=b;0==c&&(a=1);for(var d=0;d<t-1;d++)if(c+=a,0<=Za[c])return c;return b}function rb(b){Ja(m,0);var a=b;do 0<a?(a=na(t-1),m+=1,m>a&&(Ne&&Fa?(m=a,b=-b,Cb&&E(!1)):Cb?(m=a,E(!1)):m=na(0))):(a=na(0),--m,m<a&&(Ne&&Fa?(m=a,b=-b,Cb&&E(!1)):Cb?(m=a,E(!1)):m=na(t-1))),a=b;while(0>Za[m]);
Cb=Lf;void 0!=Kf&&Kf(m);Ee=a;Ja(m,1);null!=Ua&&null!=gb&&null!=gb[m]&&(Ua.innerHTML=gb[m])}function nb(b,a,c,d,e,f,k){this.bg=b;null!=b&&0==this.bg.indexOf("0x")&&(this.bg="#"+this.bg.substring(2));this.fg=a;null!=a&&0==this.fg.indexOf("0x")&&(this.fg="#"+this.fg.substring(2));this.font=c;this.fontHeight=Math.round(1.1*parseInt(c,10));this.scolor=d;null!=d&&0==this.scolor.indexOf("0x")&&(this.scolor="#"+this.scolor.substring(2));this.sblur=e;this.sxoff=f;this.syoff=k}function Va(b,a,c,d,e){k.globalAlpha=
1;k.font=b.font;var g=b.fontHeight;c=c-g-6;var f=k.measureText(d).width;1==e&&(a-=f);0==e&&(a-=f/2);5>a&&(a=5);5>c&&(c=5);c+g+3>Z&&(c=Z-g-6);a+3+f>V&&(a=V-f-6);k.save();k.beginPath();k.fillStyle=b.bg;null!=b.scolor&&(k.shadowColor=b.scolor,k.shadowBlur=b.sblur,k.shadowOffsetX=b.sxoff,k.shadowOffsetY=b.syoff);Mf=a-3;ah=c;zi=f+6;bh=g+6;k.fillRect(Mf,ah,zi,bh);k.closePath();k.restore();k.textBaseline="bottom";k.fillStyle=b.fg;k.fillText(d,a,c+g+3)}function ea(){k.clearRect(0,0,V,Z);ch=!1;if(jb){k.beginPath();
k.lineWidth=2;k.strokeStyle="white";var b=$a;1<b&&(b=2);for(var a=0;a<b;a++)1<$a&&(k.moveTo(Ub[0]/G,Fb[0]/H),k.lineTo(Ub[1]/G,Fb[1]/H)),k.moveTo(Ub[a]/G-15,Fb[a]/H),k.lineTo(Ub[a]/G+15,Fb[a]/H),k.moveTo(Ub[a]/G,Fb[a]/H-15),k.lineTo(Ub[a]/G,Fb[a]/H+15);k.closePath();k.stroke();if(3==$a){var c=X,d=O;k.moveTo(c,d);k.fillStyle=Cc;k.fillRect(c-2,d-2,5,5);b=ae;a=Math.round(c+Nf/G*Oe*(ae-$d[1]));for(var e=Math.round(d+Pe/H*Oe*(ae-$d[1])),f=0;300>f;f++){k.beginPath();k.lineWidth=1;k.strokeStyle=Cc;k.moveTo(c,
d);k.lineTo(a,e);k.stroke();k.beginPath();k.lineWidth=3;k.rect(a-2,e-2,5,5);k.stroke();if(3>a||a+3>V||3>e||e+3>Z)break;d=lc+b;d=100*Math.floor(d/60)+d%60;d%=2400;Ih?(c="AM",1200<=d?(1300<=d&&(d-=1200),c="PM"):100>d&&(d+=1200),c=Math.floor(d/100)+":"+Math.floor(Math.floor(d%100)/10)+Math.floor(d%10)+" "+c):(c=d+" ",1E3>d&&(c="0"+d),100>d&&(c="00"+d),10>d&&(c="000"+d));d=0;Math.abs(dh)<Dd+5&&(d=45*Vb);var h=e;0>Ai*dh&&0==d&&(h=e+Dd);k.font=re;c=c+" "+Hh;var l=k.measureText(c).width;k.fillStyle=qe;0===
d?(k.fillRect(a+2,h-Dd-2+d,l+4,Dd+3),k.fillStyle=Cc,k.textBaseline="bottom",k.fillText(c,a+5,h)):(k.save(),k.translate(a+5,e),k.rotate(d),k.fillRect(2,-2,l+4,Dd+3),k.fillStyle=Cc,k.textBaseline="bottom",k.fillText(c,5,Dd),k.restore());c=a;d=e;a=Math.round(c+Oe*Ai);e=Math.round(d+Oe*dh);b+=ca}}null!=Ed&&Va(lg,cj,dj,Ed,0);Ge&&(Va(Pi,9999,ci,bi[Jf],0),Bi=Mf,Ci=ah,Di=ah+bh)}if(Db){Ge&&(0==Vd?Va(mi,9999,10,lf[0],0):(Va(Zi,10,10,lf[1],0),ej=Mf+zi,Va(mi,9999,10,lf[2],0)),fj=Mf,gj=bh);k.beginPath();k.lineWidth=
2;k.strokeStyle=di;for(b=0;b<ua.length;b+=2)0==b?k.moveTo(ua[b]/G,ua[b+1]/H):k.lineTo(ua[b]/G,ua[b+1]/H);mf&4<ua.length&&k.lineTo(ua[0]/G,ua[1]/H);k.stroke();for(b=0;b<ua.length;b+=2)k.beginPath(),k.rect(ua[b]/G-2,ua[b+1]/H-2,5,5),k.stroke()}if(Rb)for(b=0;b<r.length;b++){c=r[b].type;k.beginPath();k.strokeStyle=r[b].color;k.lineWidth=r[b].width;if("0"==c||"6"==c)a=Math.atan2(r[b].xe-r[b].x,r[b].ye-r[b].y),e=r[b].x+r[b].width*Math.sin(a),f=r[b].y+r[b].width*Math.cos(a),k.beginPath(),k.moveTo(e,f),k.lineTo(r[b].xe,
r[b].ye),"0"==c&&(c=12+r[b].width/5,d=30*Vb,k.moveTo(e+c*Math.sin(a-d),f+c*Math.cos(a-d)),k.lineTo(e,f),k.lineTo(e+c*Math.sin(a+d),f+c*Math.cos(a+d)));else if("1"==c)k.arc(r[b].x,r[b].y,r[b].size,0,2*Math.PI);else if("2"==c)k.rect(r[b].x-r[b].size,r[b].y-r[b].size,2*r[b].size,2*r[b].size);else if("3"==c){k.moveTo(r[b].xp[0],r[b].yp[0]);for(e=1;e<r[b].xp.length;e++)k.lineTo(r[b].xp[e],r[b].yp[e]);k.lineTo(r[b].xp[0],r[b].yp[0])}else if("4"==c)for(k.moveTo(r[b].xp[0],r[b].yp[0]),e=1;e<r[b].xp.length;e++)k.lineTo(r[b].xp[e],
r[b].yp[e]);else"5"==c&&(k.fillStyle=r[b].color,k.font=r[b].width+"pt arial",a=k.measureText(r[b].text).width,k.fillText(r[b].text,r[b].x-a/2,r[b].y+r[b].width/2));k.stroke()}kd&&(X=oa.getX(),n=X*G,ia=N+n/B,O=oa.getY(),A=O*H,ja=M+A/J,k.beginPath(),k.strokeStyle=qh,k.lineWidth=3,k.moveTo(eh/G,fh/H),k.lineTo(Of/G,Pf/H),k.stroke(),k.closePath(),qb(),yd?(sd=Vb*be[0],td=Vb*Da[0],Qe=Vb*be[1],Re=Vb*Da[1],gh=Math.pow(Math.sin((td-sd)/2),2)+Math.cos(sd)*Math.cos(td)*Math.pow(Math.sin((Re-Qe)/2),2),gh=12742.02*
af*Math.asin(Math.min(1,Math.sqrt(gh))),b=" "+gh.toFixed(ag)+" "+zd+" ",me&&(a=z(me,"t")?(Math.atan2(Math.sin(Re-Qe)*Math.cos(td),Math.cos(sd)*Math.sin(td)-Math.sin(sd)*Math.cos(td)*Math.cos(Re-Qe))/Vb+360)%360:(Math.atan2(Math.sin(Qe-Re)*Math.cos(sd),Math.cos(td)*Math.sin(sd)-Math.sin(td)*Math.cos(sd)*Math.cos(Qe-Re))/Vb+360)%360,b=b+" ("+a.toFixed(0)+"\u00b0)")):(a=Qc*(be[0]-Da[0]),e=Ze*(be[1]-Da[1]),b=" "+Math.sqrt(a*a+e*e).toFixed(ag)+" "+zd+" ",me&&(a=Math.atan2(-a,e)/Vb,0>a&&(a+=360),z(me,"f")&&
(a+=180),360<a&&(a-=360),b=b+" ("+a.toFixed(0)+"\u00b0)")),Va(Ni,Of/G+10,Pf/H,b,-1));Nb&&Va(Mh,Ei,Fi,Gi,-1);if(bc||Td||df)if(X=oa.getX(),n=X*G,O=oa.getY(),A=O*H,0<=n&&0<=A){ia=N+n/B;ja=M+A/J;if(Td){qb();b=Da[1];yd&&180<b&&(b-=360);yd&&360<b&&(b-=360);hj=We+Da[0].toFixed(Yf)+"  "+Xe+b.toFixed(Yf);b=O;if(kd||Nb)b=O+ph.fontHeight+6;Va(ph,X+10,b,hj,-1)}if(df)for(k.fillStyle=uh,b=0;b<eb;b++)if(a=fb[b],a.isPan){if(ia>=a.x0&&ia<=a.x1&&ja>=a.y0&&ja<=a.y1){(-1===a.overlay||w[a.overlay].checked)&&k.fillRect((a.x0-
N)*B,(a.y0-M)*J,a.width*B,a.height*J);break}}else if(n>a.x0&&n<a.x1&&A>a.y0&&A<a.y1){(-1===a.overlay||w[a.overlay].checked)&&k.fillRect(a.x0,a.y0,a.width,a.height);break}if(bc&&ad&&jd)if(ia=Math.round(ia),ja=Math.round(ja),bg)ab.clearRect(0,0,1,1),ab.drawImage(Ra[m],ia-Hc,ja-Gc,1,1,0,0,1,1),aa=ab.getImageData(0,0,1,1).data,U=0,ke(!1);else for(a=0;a<W;a++)if(b=W-a-1,F[m][b].gotit&&w[b].checked&&(b==tb||null!=Ac[b]&&0<=Ac[b])){ab.clearRect(0,0,1,1);b==tb?ab.drawImage(nc[m],ia-Hc,ja-Gc,1,1,0,0,1,1):
ab.drawImage(F[m][b],ia-Hc,ja-Gc,1,1,0,0,1,1);aa=ab.getImageData(0,0,1,1).data;U=Ac[b];null!=U&&ke(b==tb||gi);break}}!pb||jb||ac||bc||null==va||(k.drawImage(va.can,0,0,va.width,va.height,va.xmin/G,va.ymin/H,va.width/G,va.height/H),Va(Mh,(va.xmin+va.xmax)/2/G,(va.ymin+va.ymax)/2/H,va.tip,0),ch=!0)}function ke(b){Qf=999;tc=rh;var a=zb[U].length-1;if(0==aa[3])tc=pf[U];else{if(sh)uc=aa[0];else if(b)hh=0,uc=aa[0],Qf=0;else for(var c=0;c<a;c++)vc[0]=aa[0]-bb[U][c],0>vc[0]*(bb[U][c+1]-aa[0]-1)||(vc[1]=aa[1]-
cb[U][c],0>vc[1]*(cb[U][c+1]-aa[1]-1)||(vc[2]=aa[2]-db[U][c],0>vc[2]*(db[U][c+1]-aa[2]-1)||(ce=yg[U][c],ih=vc[ce]/ed[U][c][ce],Hi=Math.abs(vc[Ii[ce]]-ih*ed[U][c][Ii[ce]])+Math.abs(vc[Ji[ce]]-ih*ed[U][c][Ji[ce]]),Hi<Qf&&(uc=c,Qf=Hi,hh=ih))));if(999>Qf)tc=cd[U][uc],-1!=jc[U][uc]&&(Ki=zb[U][uc],0!=hh&&(Ki+=hh*(zb[U][uc+1]-zb[U][uc])),tc=tc+" "+Ki.toFixed(jc[U][uc])+" "+bd[U][uc]);else if(b||0<ne){var d=-1;if(b)d=aa[0];else for(c=0;c<a;c++)if(Math.abs(aa[0]-bb[U][c])<ne&&Math.abs(aa[1]-cb[U][c])<ne&&
Math.abs(aa[2]-db[U][c])<ne){d=c;break}-1!=d&&(tc=cd[U][d],-1!=jc[U][d]&&(tc=tc+" "+zb[U][d].toFixed(jc[U][d])+" "+bd[U][d]))}}"hide"!=tc&&Va(Oi,X-10,O,tc,1)}function T(){jh=N-Hc;0>jh?(de=0,ee=-jh*V/ya):(de=jh,ee=0);kh=M-Gc;0>kh?(fe=0,ge=-kh*Z/za):(fe=kh,ge=0);if(jd)try{C.clearRect(0,0,V,Z);C.globalAlpha=1;if(!Uh)if(Yd&&null!=oc&&0<=ba&&oc[ba].gotit)C.drawImage(oc[ba],N*ra[ba],M*ra[ba],ya*ra[ba],za*ra[ba],0,0,V,Z);else if(Ra[m].gotit&&(null!=hg?je(Ra[m],de,fe,ya,za,ee,ge,hg):C.drawImage(Ra[m],de,
fe,ya,za,ee,ge,V,Z)),null!=Pa&&(C.globalAlpha=1,Ra[m].gotit))for(var b=0;b<Pa.length;b+=4)C.drawImage(Ra[m],Pa[b],Pa[b+1],Pa[b+2],Pa[b+3],Pa[b]/G,Pa[b+1]/H,Pa[b+2]/G,Pa[b+3]/H);if(0<W){for(b=0;b<W;b++){var a=null!=Vc?Vc[b]:b;C.imageSmoothingEnabled=Hf[a];!jg[a]&&w[a].checked&&w[a].showMe&&(null!=gf&&(C.globalAlpha=gf[a]),Yd&&0<=ba&&null!=Ca&&void 0!=Ca[a]&&Ca[a][ba][m].gotit?C.drawImage(Ca[a][ba][m],N*ra[ba],M*ra[ba],ya*ra[ba],za*ra[ba],0,0,V,Z):F[m][a].gotit&&(null==Wc||1===Wc[a]?null!=Sc&&0<=Sc[a]?
je(F[m][a],de,fe,ya,za,ee,ge,Sc[a]):C.drawImage(F[m][a],de,fe,ya,za,ee,ge,V,Z):0===Wc[a]&&C.drawImage(F[m][a],de,fe,ya,za,ee,ge,V,Z)))}if(null!=ub)for(C.globalAlpha=1,b=0;b<W;b++)if(a=null!=Vc?Vc[b]:b,F[m][a].gotit&&(Gh[a]||w[a].checked)&&ub[a])for(var c=0;c<ka[a].length;c++)C.drawImage(null!=F[m][a].origImage?F[m][a].origImage:F[m][a],ka[a][c][0],ka[a][c][1],ka[a][c][2],ka[a][c][3],ka[a][c][4]/G,ka[a][c][5]/H,ka[a][c][2]/G,ka[a][c][3]/H)}bc&&ea();li&&Pc();if(Vg)for(C.globalAlpha=1,a=0;a<eb;a++)if(null!=
fb[a]){var d=fb[a];null!=d.icon&&(d.icon.style.visibility="hidden");if((-1==d.frame||d.frame==m)&&null!=d.icon&&d.icon.gotit&&(-1==d.overlay||-1!=d.overlay&&w[d.overlay].checked)){if(d.isPan){d.zoomme&&(d.icon.style.width=Math.round(d.width*B)+"px",d.icon.style.height=Math.round(d.height*J)+"px",d.w2=Math.round(d.width*B/2),d.h2=Math.round(d.height*J/2));var e=Math.round(((d.x0-N)*B-d.w2)/G);var f=Math.round(((d.y0-M)*J-d.h2)/H);if(d.anim){if(0>=e+d.icon.width||e>=sa||0>=f+d.icon.height||f>=ta)continue;
d.icon.style.top=f+"px";d.icon.style.left=e+"px"}else C.drawImage(d.icon,d.origX,d.origY,d.width,d.height,e,f,d.width/G,d.height/H)}else C.drawImage(d.icon,d.origX,d.origY,d.width,d.height,d.x0/G,d.y0/H,d.width/G,d.height/H);d.icon.style.visibility="visible"}}Rf&&(Sf.addFrame(C,{copy:!0,delay:Li}),m==na(t-1)&&(Rf=!1,E(Ba),Sf.render()))}catch(P){fa("Error:"+P)}}function xa(b,a,c){!kf||c>=a||(C.save(),C.fillStyle="blue",C.strokeStyle="white",C.lineWidth=3,C.strokeRect(qf,rf,200,18),C.fillRect(qf,rf,
c/a*200,18),a=C.measureText(b).width,C.fillStyle="orange",C.font="14px arial",C.fillText(b,qf+100-a/2,rf+14),C.restore())}function Pc(){kf&&mc>Sa?xa("Loading Images",mc,Sa):(li=!1,Xf&&(yc.style.visibility="hidden"));Sa>=mc&&(Fa||wa(na(m)),null!=xd&&(Ea.value=xd,HAniS.doEnhance(null),xd=null),void 0!=sf&&sf(!0),null!=Bb&&(Bb.disabled=!1),null!=Mb&&(Mb.disabled=!1))}function fa(b){if(Ue&&Wf&&!Wf.closed)try{Wf.document.write(b+"<br>")}catch(a){}}function Yi(){Fa&&rb(Ee);Li=m==na(t-1)?th+Ia:Ia;T();setTimeout(function(){pj(Yi)},
Li)}function Tf(b){for(;-180>b;)b+=360;for(;180<b;)b-=360;return b}function nj(){var b,a,c,d,e,f,k,l,h=Math.PI/180;this.init=function(d){for(var c=[],g=1;g<d.length;g++)c[g]=parseFloat(d[g]);a=c[1];b=c[4]/c[5];e=c[6];f=c[7];d=this.toXY(c[2],c[3]);e=d[0];f=d[1]};this.toXY=function(g,l){c=b*Tf(l-a)*h-e;d=-b*g*h-f;return[c,d]};this.toLatLon=function(d,c){k=-(c+f)/b/h;l=Tf((d+e)/b/h+a);return[k,l]}}function mj(){var b,a,c,d,e,f,k,l,h,q,p,t,r,m,v,n,z,y,A,x,u,D,B,G,C,w,E,H,J,I,K,F=Math.PI/180;this.init=
function(d){for(var c=[],e=1;e<d.length;e++)c[e]=parseFloat(d[e]);b=c[1];a=c[2];x=0==c[8]?!1:!0;u=c[6];D=u*u;B=D*D;G=B*D;C=B*B;k=c[5]/c[7];K=c[7];x?(l=Math.cos(F*b),h=Math.sin(F*b)):(l=Math.cos(-b*F),h=Math.sin(-b*F));z=l/Math.sqrt(1-D*h*h);A=(1-u*h)/(1+u*h);n=x?Math.tan(Math.PI/4-b*F/2)/Math.pow(A,u/2):Math.tan(Math.PI/4- -b*F/2)/Math.pow(A,u/2);m=c[9];v=c[10];d=this.toXY(c[3],c[4]);m=d[0];v=d[1]};this.toXY=function(g,l){x?(e=F*g,f=F*(l-a)):(e=F*-g,f=F*(a-l));A=(1-u*Math.sin(e))/(1+u*Math.sin(e));
y=Math.tan(Math.PI/4-e/2)/Math.pow(A,u/2);w=90!=b&&-90!=b?k*z*y/n:2*k*K*y/Math.sqrt(Math.pow(1+u,1+u)*Math.pow(1-u,1-u));c=w*Math.sin(f);d=w*Math.cos(f);x||(c=-c,d=-d);q=c-m;p=d-v;return[q,p]};this.toLatLon=function(g,f){c=g+m;d=f+v;w=Math.sqrt(c*c+d*d);y=90==b||-90==b?w*Math.sqrt(Math.pow(1+u,1+u)*Math.pow(1-u,1-u))/(2*k*K):w*n/(k*z);E=Math.PI/2-2*Math.atan(y);H=Math.sin(2*E);J=Math.sin(4*E);I=Math.sin(6*E);e=E+H*D/2+5*H*B/24+H*G/12+13*H*C/360+7*J*B/48+29*J*G/240+811*J*C/11520+7*I*G/120+81*I*C/1120+
4279*Math.sin(8*E)*C/161280;x?(t=e/F,r=Math.atan2(c,d)/F+a):(t=-e/F,r=-Math.atan2(-c,-d)/F+a);return[t,Tf(r)]}}function oj(){var b,a,c,d,e,f,h,l,k,q,p,t,u,r,m,v,n,z,y,x,A,D,B,w,C,E,G,H,F,J,I,K,N,M,O,L=Math.PI/180;this.init=function(d){for(var e=[],g=1;g<d.length;g++)e[g]=parseFloat(d[g]);b=e[1];a=e[2];c=e[3];w=e[7];C=w*w;E=C*C;G=E*C;H=E*E;l=e[6]/e[8];k=Math.cos(L*b);q=Math.cos(L*a);t=Math.sin(b*L);p=Math.sin(a*L);A=k/Math.sqrt(1-C*t*t);D=q/Math.sqrt(1-C*p*p);y=Math.sqrt((1-t)/(1+t)*Math.pow((1+w*
t)/(1-w*t),w));x=Math.sqrt((1-p)/(1+p)*Math.pow((1+w*p)/(1-w*p),w));I=(Math.log(A)-Math.log(D))/(Math.log(y)-Math.log(x));K=A/(I*Math.pow(y,I));M=l*K*Math.pow(y,I);n=e[9];z=e[10];d=this.toXY(e[4],e[5]);n=d[0];z=d[1]};this.toXY=function(a,b){f=L*a;h=L*Tf(b-c);O=Math.sin(f);B=Math.sqrt((1-O)/(1+O)*Math.pow((1+w*O)/(1-w*O),w));J=l*K*Math.pow(B,I);N=I*h;d=J*Math.sin(N);e=M+J*Math.cos(N);u=d-n;r=e-z;return[u,r]};this.toLatLon=function(a,b){d=a+n;e=b+z;J=Math.abs(I)/I*Math.sqrt(d*d+(M-e)*(M-e));B=Math.pow(J/
(l*K),1/I);F=Math.PI/2-2*Math.atan(B);N=0>I?Math.atan(-d/(e-M)):Math.atan(d/(M-e));h=N/I;f=F+(C/2+5/24*E+G/12+13/360*H)*Math.sin(2*F)+(7/48*E+29/240*G+811/11520*H)*Math.sin(6*F)+(7/120*G+81/1120*H)*Math.sin(6*F)+4279/161280*H*Math.sin(8*F);m=f/L;v=Tf(c-h/L);return[m,v]}}var xh,Z,V,ta,sa,gd,Pd,G,H,Hc,Gc,ei,fi,Ob,Pb,yc,Xf,oa,Ue,Wg,Wf,Lc,lh,Uc,u,y,xf,zf,Wa,yf,Ic,ye,ij,jj,sb,C,ab,zc,k,we,Ig,jh,kh,de,fe,ee,ge,Xc,mg,jf,ki,ng,Jc,t,Aa,Yh,hb,fd,Ga,qd,W,jg,ec,Vc,L,Kc,fc,Fd,ha,Nh,Ra,F,Dg,Vi,hi,w,gf,Ce,Nb,Gi,
Ei,Fi,Cd,Jb,zh,K,Ah,ve,Eg,X,O,n,A,ia,ja,ya,za,N,M,Ge,ob,Lb,Xi,Fa,Ba,wf,m,Kf,Ee,Ne,Zd,Fc,Nd=!0,ef,Af,Lg,Kg,Ye,Ve,f,Ia,gc,Zc,Wd,sf,ug,th,Li,Ad,vh,Hf,Ea,Qd,Tc,tb,xd,Xa,nc,hd,Be,Gg,tf,hg,Od,xe,xi,rd,ib,Xg,Yg,Zg,$g,bj,sc,Sc,Za,Xd,Ef,Ff,wi,Eb,yi,Rg,mh,ti,ui,vi,pe,yh,fb,eb,Vg,og,df,dg,uh,xg,pa,dd,Me,ii,Ab,Qa,aa,nh,Ya,uf,pb,Rd,Hg,Ae,va,ch,Bc,Bd,ra,ba,oc,id,Ca,Ta,Yd,gb,Ua,Nc,Tg,Gf,pd,Sg,jd,wd,Kb,yb,xb,Qb,ic,hc,ff,Bb,Rf,Sf,Mb,Md,ld,Db,Vd,lf,vg,mf,of,di,ua,Zi,mi,fj,ej,gj,pc,jb,$a,Ub,Fb,$d,Bi,bi,Ci,Di,ci,Pi,
wb,Oe,Nf,Pe,Mi,Vb,te,Cg,Ai,dh,ae,ca,Jf,lc,hf,Hh,Cc,qe,re,Dd,Ih,Jh,aj,Pg,Qg,Ng,Og,Ie,r,Mg,ri,rc,si,qa,Rb,od,Je,nd,md,Df,$i,Le,Ke,Mc,Sb,oi,pi,Ka,Ph,Oh,Kd,B,J,vf,If,ai,Dc,se,$h,Zh,Ha,Yc,Ld,Uf,tg,Bh=!1,Ch,Dh,Eh,kg,Fh,Cb,Lf,Bf,ni,De,Fe,La,Cf,He,Fg,qc,ac,eh,fh,ag,$e,yd,Mf,ah,zi,bh,ji=!0,ze,oh,Of,Pf,Ni,qh,$f,Ma,Zf,bf,kd,Qc,Ze,zd,me,sd,td,Qe,Re,gh,af,Mh,ig,Sd,Td,Yf,We,Xe,ph,kc,Da,be,hj,zg,Ag,Ui,Bg,Pa,Tb,Ug,Wc,ub,ka,Gh,Jg,nf,$c,Vh,Xh,Wh,Ac,bc,Ud,cf,ad,bd,cd,jc,ce,Qf,Oi,rh,ne,sh,bg,lg,Kh,Lh,Ed,cj,dj,uc,hh,
ih,Ii,Ji,vc,U,Hi,tc,Ki,zb,v,ed,gi,bb,cb,db,ue,yg,pf,kj,oe,cg,Rc,kf,eg,fg,gg,cc,dc,wh,li,qf,rf,Sa,mc,Gd,Uh,pg,Hd,qg,Id,rg,Qh,Rh,Th,Sh,Jd,sg,le,vb,qj="N NNE NE ENE E ESE SE SSE S SSW SW WSW W WNW NW NNW N".split(" "),pj=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame||function(b){setTimeout(b,10)},p=function(b){return document.createElement(b)},z=function(b,a){return null==b?!1:0==b.trim().toLowerCase().indexOf(a)},Wi=
function(b,a){if(null!=b)return b=b.trim(),b.lastIndexOf(a)===b.length-1},Ti=function(b){void 0==lh&&(lh=p("textarea"));lh.innerHTML=b;return lh.value},qi=function(b,a,c){var d=p("select");d.style.width="70px";d.style.margin="5px";for(var e=0;e<b.length;e++){var g=p("option");g.innerHTML=b[e];g.value=a[e];d.add(g)}d.addEventListener("change",c,!1);return d},Si=function(b){b=b.split(",");L=Array(t);for(var a=0;a<b.length;a++){var c=b[a].split("&");W=b.length;for(var d=0;d<t;d++)0===a&&(L[d]=Array(W)),
L[d][a]=c[1==c.length?0:d].trim(),null!=vb?L[d][a]=(vb+L[d][a]).trim():null!=ha&&(L[d][a]=(ha+L[d][a]).trim())}wd=!1},Qi=function(b){b=b.split(",");t=b.length;Aa=Array(t);for(var a=0;a<t;a++)Aa[a]=null!=ha?ha+b[a].trim():b[a].trim();wd=!1;t>W&&(W=0)},Ri=function(b,a,c){var d=b;null!=ha&&(d=ha+b);Aa=Array(t);for(var e=0;e<t;e++){b=e*c+a;if(0<=d.indexOf("*"))Aa[e]=d.replace("*",b);else if(0<=d.indexOf("?")){for(var g=d;0<=g.lastIndexOf("?");){var h=g.lastIndexOf("?");g=g.substring(0,h)+b%10+g.substring(h+
1);b=Math.floor(b/10)}Aa[e]=g}else Aa[e]=d+e;fa("image filename = "+Aa[e])}z(f.reverse_order,"t")&&Aa.reverse();wd=!1;t>W&&(W=0)};HTMLCanvasElement.prototype.toBlob||Object.defineProperty(HTMLCanvasElement.prototype,"toBlob",{value:function(b,a,c){c=window.atob(this.toDataURL(a,c).split(",")[1]);for(var d=c.length,e=new Uint8Array(d),g=0;g<d;g++)e[g]=c.charCodeAt(g);b(new Blob([e],{type:a||"image/png"}))}});this.setup=function(b,a,e,d){void 0==a&&(a="MORdivcan");yf=a;ze=e;void 0!=ze&&"function"!=
typeof ze&&(ze=null);oh=void 0!=d?d.split("\n"):null;u=document.getElementById(a);le="center";u.align=le;Wa=p("div");Wa.setAttribute("style","position:relative;border:0px;margin:0px;padding:0px;-webkit-user-select:none; -moz-user-select:none; -ms-user-select:none; user-select:none; -webkit-tap-heightlight-color:transparent;");sb=p("canvas");sb.setAttribute("style","position:absolute;top:0;left:0;z-index:1;");C=sb.getContext("2d");zc=p("canvas");zc.setAttribute("style","position:absolute;top:0;left:0;z-index:12;");
k=zc.getContext("2d");k.imageSmoothingEnabled=!1;we=p("canvas");we.setAttribute("style","position:absolute;top:0;left:0;z-index:10;");Ig=we.getContext("2d");Ig.imageSmoothingEnabled=!1;Ic=p("div");Ic.setAttribute("style","position:absolute;top:0;left:0;z-index:5;overflow:hidden;border-width:0px;padding:0px;margin:0px;");ye=p("div");ye.setAttribute("style","position:absolute;top:0;left:0;z-index:10;overflow:hidden;border-width:0px;padding:0px;margin:0px;");ye.appendChild(we);Od=p("canvas");Wa.appendChild(ye);
Wa.appendChild(sb);Wa.appendChild(zc);Wa.appendChild(Ic);u.appendChild(Wa);oa=new PEvs(Wa,HAniS.down,HAniS.up,HAniS.move,HAniS.drag,null,HAniS.canTip);u.setAttribute("tabindex",0);u.addEventListener("keyup",function(a){Rb||Ve||(Kg=Lg=Af=!1,Ye&&(a.preventDefault(),a.stopPropagation()))},!1);u.addEventListener("keypress",function(a){Rb||Ve||!Ye||(a.preventDefault(),a.stopPropagation())},!1);u.addEventListener("keydown",function(a){Rb||Ve||(Ye&&(a.preventDefault(),a.stopPropagation()),Af=a.ctrlKey?!0:
!1,Lg=a.shiftKey?!0:!1,Kg=a.altKey?!0:!1,37==a.keyCode?(E(!1),rb(-1),T()):39==a.keyCode?(E(!1),rb(1),T()):32==a.keyCode?HAniS.toggleIsLooping():82==a.keyCode&&a.altKey&&HAniS.resetZoom())},!1);u.addEventListener("mouseenter",function(a){u.focus({preventScroll:!0})},!1);u.style.outlineWidth="0px";u.style.outline="none";Vb=.01745329252;Lb=m=0;Ne=!1;Ee=1;Lf=Cb=!1;Ba=Fa=!0;Rf=!1;eb=W=t=0;dg=df=!1;ef=!0;Vc=null;hb=[];fd=!1;Ga=0;qd=[];Fc=!0;Ia=500;gc=100;Zc=2E3;ug=30;th=0;cg=6E4;Rc=null;Xc=oe=!1;jf=!0;
Jc=[];Fd=vb=ha=null;Dg=!1;ra=Nh=null;Yd=!1;ba=-1;Ld=!1;If=vf=J=B=1;Uf=!1;M=N=za=ya=ja=ia=A=n=O=X=0;ai=!1;Nd=ji=!0;Tg=Xf=Uc=!1;pe=mh=-1;Za=[];Ab=0;Vg=!1;pa=null;dd=-1;xg=0;Me=!1;Ua=null;rf=qf=Sa=mc=0;gi=!1;U=0;Nb=ng=og=jd=!1;eh=fh=Of=Pf=0;kd=ac=!1;Ma=[];Ma.push("default");Ma.push("default");Zf="default";Td=!1;bf="default";kc=null;Da=[0,0];be=[0,0];pb=Fg=$e=!1;Bd=!0;va=Bc=null;Db=ch=!1;mf=!0;$f="default";Ge=!0;ua=[];bc=bg=!1;cf="default";ad=!1;Ii=[1,0,0];Ji=[2,2,1];vc=[];Ac=[];Tc=Qd=jb=!1;hf=Jf=0;Tb=
zf=xf=y=Eb=null;Ug=0;Ye=!0;Rb=Ve=Lg=Kg=Af=!1;Md=27;a=p("canvas");a.height=1;a.width=1;ab=a.getContext("2d");ab.imageSmoothingEnabled=!1;Hg=p("canvas");Ue=!1;"string"===typeof b?0>b.indexOf("\n")?Gb(b):c(b.split("\n")):c(b)};this.newBasenames=function(b,a,c,d){jd=!1;Ba=Fa;E(!1);t=d;Ri(b,a,c);Fc=!0;Wb()};this.newFilenames=function(b){jd=!1;Ba=Fa;E(!1);Qi(b);Fc=!0;Wb()};this.newOverlayFilenames=function(b){jd=!1;Ba=Fa;E(!1);Si(b);Fc=!0;Wb()};this.newProbeTable=function(b){ad=!1;q(b.trim())};this.reloadFOF=
function(){fa("reload FoF = "+Rc);wc("r");wd?lj(kj,!1):(Ba=null==wf?!0:Fa,Fc=!0,Wb())};this.getFOF=function(){var b=f.file_of_filenames.trim();HAniS.newFOF(null!=Fd?Fd+b:b,!0)};this.newFOF=function(b,a){HAniS.resetZoom();lj(b,a)};var lj=function(b,a){var c,d,e,f,h=new XMLHttpRequest,l,k,p,r,m,v,n,w=null,z=!1;ii=Ab;jd=!1;Ba=Fa;E(!1);a&&wa(Lb);Ab=t=0;Aa=[];K=Ya=null;Dg=!1;Eg=[];for(ve=null;Ic.hasChildNodes();)Ic.removeChild(Ic.lastChild);uf=0;Yd=pb=Rd=!1;Ca=id=oc=null;Ta=[];Nc=-1;L=[];var y=!1;if(null==
wb||null!=te)wb=[];fa("new FOF="+b);jb&&(null!=pc&&(I(pc,!0,"extrap on"),u.style.cursor="default",E(Ba),$a=-1),jb=!1,ea());Db&&(null!=ld&&(I(ld,!0,"mark on"),u.style.cursor="default",E(Ba),Vd=-1),Db=!1,ea());h.onload=function(){var a=this.responseText.split("\n");for(c=0;c<a.length;c++)if(!(2>a[c].length)&&(l=a[c].trim(),fa("FOF: "+l),0!=l.indexOf("#")))if(0==l.indexOf("frame_labels"))m=l.split("="),gb=m[1].split(",");else if(0==l.indexOf("redirect"))for(m=l.split("="),n=m[1].split(","),ve=n[0].trim(),
d=1;d<n.length;d++){var b=parseInt(n[d],10)-1;Eg[b]=!0}else if(0==l.indexOf("framenumber_index_values"))m=l.split("="),ig=m[1].split(",");else if(0==l.indexOf("slice")){m=l.split("=");n=m[1].split(",");K=[];for(d=0;d<n.length;d++)K[d]=parseInt(n[d],10);K[2]=K[2]-K[0]+1;K[3]=K[3]-K[1]+1;4<K.length&&(K[6]=K[6]-K[4]+1,K[7]=K[7]-K[5]+1)}else if(0==l.indexOf("fof_extension"))m=l.split("="),w=m[1].trim();else if(0==l.indexOf("probe_table"))m=l.split("="),ad=!1,q(m[1].trim());else if(0==l.indexOf("image_base"))m=
l.split("="),ha=m[1].trim();else if(0==l.indexOf("overlay_base"))m=l.split("="),vb=m[1].trim();else if(0==l.indexOf("high_res_basemap")){m=l.split("=");n=m[1].split(",");id=[];for(d=0;d<n.length;d++)id[d]=n[d].trim(),null!=ha&&(id[d]=ha+id[d]);Yd=!0}else if(0==l.indexOf("high_res_overlay"))for(m=l.split("="),v=m[1].split("&"),e=0;e<v.length;e++){n=v[e].split(",");Nc=parseInt(n[0].trim(),10)-1;Ta[Nc]=[];for(d=1;d<n.length;d++)Ta[Nc][d-1]=n[d].trim(),Wi(Ta[Nc][d-1],"/")||(null!=vb?Ta[Nc][d-1]=vb+Ta[Nc][d-
1]:null!=ha&&(Ta[Nc][d-1]=ha+Ta[Nc][d-1]));Yd=!0}else if(0==l.indexOf("high_res_zoom")){m=l.split("=");n=m[1].split(",");ra=[];for(d=0;d<n.length;d++)ra[d]=parseFloat(n[d].trim());Zb()}else if(0==l.indexOf("hoverzone"))he(l);else if(0==l.indexOf("hotzone"))Oa(l);else if(0==l.indexOf("hotspot"))z||(fb=null,eb=0,z=!0),Xb(l);else if(0==l.indexOf("toggle_onoff"))m=l.split("="),Gf=m[1].split(",");else if(0==l.indexOf("coordinates"))m=l.split("="),D(m[1]);else if(0==l.indexOf("fof_substitute"))b=l.indexOf("="),
n=l.substring(b+1).split(","),Dg=!0,hi=n[0].trim(),Vi=n[1].trim();else if(0==l.indexOf("map_scale"))m=l.split("="),n=m[1].split(","),Qc=parseFloat(n[0]),Ze=1<n.length?parseFloat(n[1]):Qc;else if(0==l.indexOf("times")){m=l.split("=");n=m[1].split(",");for(c=0;c<n.length;c++)wb[c]=parseInt(n[c].trim(),10);y=!0}else{null!=te&&(b=l.match(te),null!=b&&2==b.length?(wb.push(parseInt(b[1],10)),fa("+ + + Extrap time = "+b[1]),y=!0):fa("+ + + Cannot parse times using "+te+" from line: "+l));e=l.indexOf(" ");
0>e&&(e=l.length);Aa[t]=l.substring(0,e).trim();null!=ha&&(Aa[t]=ha+Aa[t]);l=l.substring(e+1);b=l.indexOf('"');0<=b&&(null==gb&&(gb=[]),e=l.substring(b+1),b=e.indexOf('"'),0<=b&&(gb[t]=e.substring(0,b),0==t&&(Ua.innerHTML=gb[0])));L[t]=[];b=l.indexOf("overlay");if(0<=b)for(k=l.substring(b),b=k.indexOf("="),0>b&&fa("Cannot find a = sign in "+k),p=k.substring(b+1),k=p.trim(),p=k.split(","),W=Math.max(W,p.length),fa("numOverlays set to "+W),f=0;f<p.length;f++)L[t][f]=p[f].trim(),null!=ve&&Eg[f]?L[t][f]=
(ve+L[t][f]).trim():null!=vb?L[t][f]=(vb+L[t][f]).trim():null!=ha&&(L[t][f]=(ha+L[t][f]).trim());t+=1}y&&Y(wb);null!=w?(a=new XMLHttpRequest,a.onload=function(){var a=this.responseText.split("\n");for(c=0;c<a.length;c++)2>a[c].length||(r=a[c].trim(),fa("ext_FOF: "+r),0!=r.indexOf("#")&&(0==r.indexOf("hotzone")?Oa(r):0==r.indexOf("hotspot")&&Xb(r)));ma()},a.onerror=function(){ma()},a.open("get",w+"?"+Math.round(1E5*Math.random()),!0),a.send()):ma()};kj=b;h.open("get",b+"?"+Math.round(1E5*Math.random()),
!0);h.send()};this.setWindowSize=function(b,a){if(null!=u){u.style.height=a+"px";u.style.width=b+"px";u.style.padding="0px";ij=a=a-(null!=xf?xf.offsetHeight:0)-(null!=zf?zf.offsetHeight:0)-(null!=Eb?Eb.offsetHeight:0)-Ug*(null!=Tb?Tb.offsetHeight:0);jj=b;var c=a*sa/ta;c>b&&(c=b,a=b*ta/sa);a=Math.floor(a);c=Math.floor(c);Nd||(Uc?ud(jj,ij):ud(c,a),ea())}};this.drag=function(b){Db||(X=oa.getX(),O=oa.getY(),Rb?(b=r.length-1,r[b].xe=X,r[b].ye=O,r[b].xp.push(X),r[b].yp.push(O),r[b].size=Math.round(Math.sqrt(Math.pow(X-
r[b].x,2)+Math.pow(O-r[b].y,2)))):(n=X*G,A=O*H,kd=Nb=!1,ac&&(!$e||$e&&b.shiftKey)?(Of=n,Pf=A,kd=!0):(Ha&&J!=If?(N=ia-n/B,M=ja-A/J,Oc(),ia=Math.round(N+n/B),ja=Math.round(M+A/J),void 0!=Zd&&Zd(["drag",B,J,ia,ja,n,A,N,M,ya,za])):Db||jb||!pb||(va=null,Bd&&0<=n&&0<=A&&(aa=Ae.getImageData(n,A,1,1).data,0!=aa[3]&&(va=Ya[aa[3]-1]))),Uf=!0,T())),ea())};this.resetZoom=function(){B=vf;J=If;ba=-1;null!=Ka&&(I(Ka,!0,"zoom on"),Ha=!1);ia=n;ja=A;M=N=0;za=ta;ya=sa;Zb();T();Rd&&(pb=!0);void 0!=Zd&&Zd(["reset",0,
0])};this.canTip=function(){var b;Nb=!1;X=oa.getX();n=X*G;O=oa.getY();A=O*H;if(!((Db||jb)&&A<Di&&A>Ci&&n>Bi)){ia=Math.round(N+n/B);ja=Math.round(M+A/J);if(0!=Ab)for(b=0;b<Ab;b++)if(Qa[b].overlay>=W)fa(" Error...hotzone overlay # "+Qa[b].overlay+" > number of overlays = "+W);else if(w[Qa[b].overlay].checked&&(ab.clearRect(0,0,1,1),ab.drawImage(F[m][Qa[b].overlay],ia,ja,1,1,0,0,1,1),aa=ab.getImageData(0,0,1,1).data,nh=(aa[0]<<16)+(aa[1]<<8)+aa[2],nh==Qa[b].color)){Nb=!0;Ei=X;Fi=O;Gi=Qa[b].tip;break}if(0!=
eb)for(b=eb-1;0<=b;b--)if(null!=fb[b]){var a=fb[b];if(-1==a.frame||a.frame==m)if(-1==a.overlay||w[a.overlay].checked){var c=!1;if(a.isPan)if(a.isIcon){var d=(a.x0-N)*B-a.w2;var e=(a.y0-M)*J-a.h2;n>d&&n<d+a.width&&A>e&&A<e+a.height&&(c=!0)}else d=(a.x0-N)*B,e=(a.y0-M)*J,n>d&&n<d+a.width*B&&A>e&&A<e+a.height*J&&(c=!0);else n>a.x0&&n<a.x1&&A>a.y0&&A<a.y1&&(c=!0);if(c&&null!=a.tip){Nb=!0;Ei=X;Fi=O;Gi=fb[b].tip;break}}}ea()}};this.move=function(){if(!jb&&pb&&(va=null,Bd)){var b=oa.getX()*G,a=oa.getY()*
H;0<=b&&0<=a&&(aa=Ae.getImageData(b,a,1,1).data,0!=aa[3]&&(va=Ya[aa[3]-1]))}jb&&2<=$a&&(X=oa.getX(),n=X*G,O=oa.getY(),A=O*H);ea()};this.down=function(){Nb&&(Nb=!1,ea());X=oa.getX();n=X*G;O=oa.getY();A=O*H;eh=n;fh=A;Of=eh;Pf=fh;ia=Math.round(N+n/B);ja=Math.round(M+A/J);ac&&(qb(),be[0]=Da[0],be[1]=Da[1]);Uf=!1;if(Rb){var b={};b.x=X;b.y=O;b.xe=X;b.ye=O;b.xp=[X];b.yp=[O];b.type=Le.value;b.color=Ke.value;b.width=Mc.value;b.text=Sb.value;b.size=0;r.push(b)}};this.up=function(b){Nb=!1;if(!Rb){if(jb||Db){X=
oa.getX();n=X*G;O=oa.getY();A=O*H;if(Db){Vd=1;if(0<Vd&&A/H<gj){if(n/G>fj){ua.pop();ua.pop();0==ua.length&&(Vd=0);ea();return}if(n/G<ej){ea();b=window.open("","Mark Points");b.document.write("<div>Marked Points<br>");for(var a=[],c=0;c<ua.length;c+=2)ia=N+ua[c]/B,ja=M+ua[c+1]/J,qb(),b.document.write(Da[0].toFixed(4)+","+Da[1].toFixed(4)+"<br>"),0==c&&(a[0]=Da[0],a[1]=Da[1]);mf&&b.document.write(a[0].toFixed(4)+","+a[1].toFixed(4)+"<br>");return}}ua.push(n);ua.push(A);ea();return}if(3>$a)if(Ub[$a]=
n,Fb[$a]=A,$d[$a]=Cg[m],0==$a)$a=1,wa(na(t-1)),Jf=1,Ed=null;else{Mi=$d[1]-$d[0];Nf=(Ub[1]-Ub[0])/Mi;Pe=(Fb[1]-Fb[0])/Mi;if(null!=lg&&null!=Qc){c=Nf*Qc;var d=Pe*Ze;a=Math.round(60*Math.sqrt(c*c+d*d));c=Math.atan2(c,-d)/Vb;0>c&&(c+=360);Ed=Kh+qj[Math.round(c/22.5)]+" at "+a+" "+Lh;cj=Ub[0];dj=0<Pe?Fb[0]-15:Fb[0]+30}a=parseInt(re,10);ca=Math.round(Math.abs(4*(a+4)/Nf));ae=Math.round(Math.abs(2*(a+4)/Pe));ae<ca&&(ca=ae);120<ca?ca=120*Math.floor(ca/120)+60:90<ca?ca=120:60<ca?ca=90:30<ca?ca=60:15<ca?ca=
30:10<ca?ca=15:5<ca?ca=10:2<ca?ca=5:0==ca&&(ca=1);ae=$d[1]/ca*ca+ca;Oe=1;Jh&&(Oe=-1);Ai=Nf*ca;dh=Pe*ca;wa(na(t-1));$a=3;Jf=2}else if(A/H<Di&&A/H>Ci&&n/G>Bi&&3==$a){$b();ea();return}ea()}if(kd)kd=!1,ea();else if(null!=qc&&Ha&&(ac=!1,I(qc,!0,"distance on")),Uf)Uf=!1;else if(b.altKey)HAniS.resetZoom();else if(pb&&null!=va&&ch)vd(va,"z");else{X=oa.getX();n=X*G;O=oa.getY();A=O*H;if(0!=Ab)for(a=0;a<Ab;a++)if(Qa[a].overlay>=W)fa(" Error...hotzone overlay # "+Qa[a].overlay+" > number of overlays = "+W);else if(w[Qa[a].overlay].checked&&
(ab.clearRect(0,0,1,1),ab.drawImage(F[m][Qa[a].overlay],Math.floor(ia),Math.floor(ja),1,1,0,0,1,1),aa=ab.getImageData(0,0,1,1).data,nh=(aa[0]<<16)+(aa[1]<<8)+aa[2],nh==Qa[a].color)){vd(Qa[a],"z");return}if(0!=eb)for(a=eb-1;0<=a;a--)if(null!=fb[a]){var e=fb[a];if(!(-1!=e.frame&&e.frame!=m||e.fromfile||-1!=e.overlay&&!w[e.overlay].checked)){var f=!1;e.isPan?e.isIcon?(c=(e.x0-N)*B-e.w2,d=(e.y0-M)*J-e.h2,n>c&&n<c+e.width&&A>d&&A<d+e.height&&(f=!0)):(c=(e.x0-N)*B,d=(e.y0-M)*J,n>c&&n<c+e.width*B&&A>d&&
A<d+e.height*J&&(f=!0)):n>e.x0&&n<e.x1&&A>e.y0&&A<e.y1&&(f=!0);if(f){vd(fb[a],"s");return}}}Ha&&(pb=!1,ie(b.ctrlKey||Af||b.which&&3==b.which||b.button&&2==b.button));T();ea()}}};this.wheel=function(b){Yh?rb(b):Ha&&(X=oa.getX(),n=X*G,O=oa.getY(),A=O*H,ia=Math.round(N+n/B),ja=Math.round(M+A/J),ie(-1==b))};this.toggleAutoRefresh=function(){oe?(I($c,!1,"autorefresh off"),null!=Rc&&clearInterval(Rc),oe=!1):(I($c,!0,"autorefresh on"),Rc=setInterval("HAniS.reloadFOF();",cg),oe=!0)};this.toggleLoopRock=function(){Ne?
(I(De,!0,"looprock rock"),Ne=!1):(I(De,!1,"looprock loop"),Ne=!0)};this.toggleLoopHalt=function(){Cb?(I(Fe,!0,"loophalt halt"),Lf=Cb=!1):(I(Fe,!1,"loophalt loop"),Lf=Cb=!0)};this.toggleExtrap=function(){jb?(null!=pc&&(I(pc,!0,"extrap on"),u.style.cursor=Ma.pop(),null!=Kb&&(Kb.disabled=!1),E(Ba),Ha=Zh,$a=-1),jb=!1,ea()):(null!=pc&&(jb=!0,Ed=null,Ma.push(u.style.cursor),u.style.cursor="crosshair",I(pc,!1,"extrap off"),Ba=Fa,null!=Kb&&(Kb.disabled=!0),Fa=!1,Zh=Ha,Ha=!1,HAniS.resetZoom(),$b(),ea()),T())};
this.doEnhance=function(b){if(Qd||Tc){var a=Xa[0].height,c=Xa[0].width;b=parseInt(Ea.value,10);0<=b?(Xg=bb[b],Yg=cb[b],Zg=db[b],$g=ue[b],Ac[tb]=b):Ac[tb]=null;var d=a*c*4;for(c=0;c<nc.length;c++)if(Xa[c].gotit){Xa[c].gotit=!1;var e=tf[c].data;var f=Gg[c];if(0>b)for(a=0;a<d;a+=4)e[a]=f[a],e[a+1]=f[a+1],e[a+2]=f[a+2],e[a+3]=f[a+3];else for(a=0;a<d;a+=4)ib=f[a],ib===f[a+1]&&ib===f[a+2]&&(e[a]=Xg[ib],e[a+1]=Yg[ib],e[a+2]=Zg[ib],e[a+3]=$g[ib]);hd[c].putImageData(tf[c],0,0);Xa[c].gotit=!0}}};this.overClick=
function(b){var a;if(b.target.checked)for(a=0;a<w.length;a++)b.target!=w[a]&&0!=b.target.name&&b.target.name==w[a].name&&(w[a].checked=!1);Bd=!0;for(a=0;a<fc.length;a++)b.target!=w[a]&&Ib(a),null!=Bc&&!Bc[a]&&w[a].checked&&(Bd=!1),null!=Ea&&a===tb&&(Ea.disabled=!w[a].checked);T()};this.toggleIsLooping=function(){Fa?(Fa=!1,I(Kb,!0,"startstop start")):(Fa=!0,I(Kb,!1,"startstop stop"),Lf=Cb,Cb=!1)};this.toggleZooming=function(){Ha?(HAniS.resetZoom(),I(Ka,!0,"zoom on")):(I(Ka,!1,"zoom off"),Ha=!0,null!=
qc&&(ac=!1,I(qc,!0,"distance on")),Rd&&(pb=!0),jb&&HAniS.toggleExtrap())};this.togup=function(b){mh=-1};this.togdown=function(b){var a=Rg.getX();Rg.getY();for(var c=yi,d=0;d<Za.length;d++){if(a>c&&a<c+Xd){if(d==mh)break;if(b.shiftKey){0<=Za[d]&&(E(!1),wa(d));break}a=0;!b.ctrlKey&&0<=Za[d]&&(a=-1);Ja(d,a);mh=d;break}c=c+Xd+Ff}};this.makeMP4=function(){var b=Mb.innerHTML;Ba=Fa;E(!1);Ee=1;wa(na(Lb));Mb.innerHTML="Working";HME.createH264MP4Encoder().then(function(a){var c,d,e,h,k;return $jscomp.asyncExecutePromiseGeneratorProgram(function(g){switch(g.nextAddress){case 1:a.width=
V,a.height=Z,a.frameRate=Math.max(1,Math.round(1E3/Ia)),a.quantizationParameter=Md,a.initialize();case 2:return T(),a.addFrameRgba(C.getImageData(0,0,V,Z).data),g.yield(new Promise(function(a){return window.requestAnimationFrame(a)}),4);case 4:if(m>=na(t-1)){g.jumpTo(3);break}rb(1);g.jumpTo(2);break;case 3:a.finalize();Mb.innerHTML=b;c=a.FS.readFile(a.outputFilename);d=f.mp4_prompt;e=f.mp4_filename;null==e&&(e="hanimate.mp4");h=e;if(null!=d&&(h=window.prompt(d,h),null==h))return a.delete(),E(Ba),
g.return();k=document.createElement("a");k.href=URL.createObjectURL(new Blob([c],{type:"video/mp4"}));k.download=h;k.click();a.delete();E(Ba);g.jumpToEnd()}})})};this.makeAniGIF=function(){if(!Rf){var b=Bb.innerHTML;Sf=new GIF({workers:4,debug:!1,quality:10,width:V,height:Z,repeat:0});Sf.on("finished",function(a){Bb.innerHTML=b;var c=f.anigif_prompt,d=f.anigif_filename;null==d&&(d="hanimate.gif");if(null!=c&&(d=window.prompt(c,d),null==d))return;c=document.createElement("a");c.href=URL.createObjectURL(a);
c.download=d;c.click();setTimeout(function(){URL.revokeObjectURL(a)},3E4)});Sf.on("progress",function(a){Bb.innerHTML=Math.round(100*a)+"%"});Ba=Fa;E(!1);Ee=1;Rf=!0;wa(na(Lb));T();E(!0);Bb.innerHTML="Loading"}};this.doneLoading=function(b){sf=b};this.getCustomButton=function(){return of};this.dwellChanged=function(b){Wd=b};this.getDwell=function(){return Ia};this.frameChanged=function(b){Kf=b};this.getFrame=function(){return m};this.showFrame=function(b){wa(na(b));T()};this.zoomChanged=function(b){Zd=
b};this.showZoom=function(b){"reset"===b[0]?HAniS.resetZoom():(B=b[1],J=b[2],ia=b[3],ja=b[4],n=b[5],A=b[6],N=b[7],M=b[8],ya=b[9],za=b[10],Oc(),T())}};
